# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2014.4
# Copyright (C) 2014 Xilinx Inc. All rights reserved.
# 
# ==============================================================

#
# Settings for Xilinx implementation flow
#
set top_module qam_dem_top
set language vhdl
set family spartan6
set device xc6slx45t
set package fgg484
set speed -3
set clock ap_clk
set fsm_ext "none"

# For customizing the implementation flow
set optimization_goal speed    ;# speed|area
set optimization_effort high   ;# normal|high
set register_duplication false ;# true|false
set register_balancing no      ;# yes|no
set par_effort high            ;# std|high|extra
set add_io_buffers false       ;# true/false
