// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "qam_dem_top_mounstrito.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic qam_dem_top_mounstrito::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic qam_dem_top_mounstrito::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st1_fsm_0 = "1";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st2_fsm_1 = "10";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st3_fsm_2 = "100";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st4_fsm_3 = "1000";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st5_fsm_4 = "10000";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st6_fsm_5 = "100000";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<15> qam_dem_top_mounstrito::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> qam_dem_top_mounstrito::ap_const_lv1_1 = "1";
const sc_lv<28> qam_dem_top_mounstrito::ap_const_lv28_0 = "0000000000000000000000000000";
const sc_lv<16> qam_dem_top_mounstrito::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_1 = "1";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_3 = "11";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_2 = "10";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_4 = "100";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_8 = "1000";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_5 = "101";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_6 = "110";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_7 = "111";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_9 = "1001";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_A = "1010";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_B = "1011";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_C = "1100";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_D = "1101";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_E = "1110";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_1A = "11010";
const sc_lv<11> qam_dem_top_mounstrito::ap_const_lv11_0 = "00000000000";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_18 = "11000";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_19 = "11001";
const sc_lv<2> qam_dem_top_mounstrito::ap_const_lv2_0 = "00";
const sc_lv<2> qam_dem_top_mounstrito::ap_const_lv2_3 = "11";
const sc_lv<5> qam_dem_top_mounstrito::ap_const_lv5_0 = "00000";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_14 = "10100";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_12 = "10010";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_13 = "10011";
const sc_lv<14> qam_dem_top_mounstrito::ap_const_lv14_1FFF = "1111111111111";
const sc_lv<14> qam_dem_top_mounstrito::ap_const_lv14_2000 = "10000000000000";
const sc_lv<14> qam_dem_top_mounstrito::ap_const_lv14_0 = "00000000000000";
const sc_lv<8> qam_dem_top_mounstrito::ap_const_lv8_0 = "00000000";
const sc_lv<9> qam_dem_top_mounstrito::ap_const_lv9_9 = "1001";
const sc_lv<9> qam_dem_top_mounstrito::ap_const_lv9_1F7 = "111110111";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_1C = "11100";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_1B = "11011";
const sc_lv<28> qam_dem_top_mounstrito::ap_const_lv28_7FFFFFF = "111111111111111111111111111";
const sc_lv<28> qam_dem_top_mounstrito::ap_const_lv28_8000000 = "1000000000000000000000000000";
const sc_lv<32> qam_dem_top_mounstrito::ap_const_lv32_F = "1111";
const sc_lv<10> qam_dem_top_mounstrito::ap_const_lv10_3FF = "1111111111";
const sc_lv<2> qam_dem_top_mounstrito::ap_const_lv2_1 = "1";

qam_dem_top_mounstrito::qam_dem_top_mounstrito(sc_module_name name) : sc_module(name), mVcdFile(0) {
    cos_lut_U = new qam_dem_top_mounstrito_cos_lut("cos_lut_U");
    cos_lut_U->clk(ap_clk);
    cos_lut_U->reset(ap_rst);
    cos_lut_U->address0(cos_lut_address0);
    cos_lut_U->ce0(cos_lut_ce0);
    cos_lut_U->q0(cos_lut_q0);
    cos_lut_U->address1(cos_lut_address1);
    cos_lut_U->ce1(cos_lut_ce1);
    cos_lut_U->q1(cos_lut_q1);
    qam_dem_top_mul_16s_12s_27_2_U1 = new qam_dem_top_mul_16s_12s_27_2<1,2,16,12,27>("qam_dem_top_mul_16s_12s_27_2_U1");
    qam_dem_top_mul_16s_12s_27_2_U1->clk(ap_clk);
    qam_dem_top_mul_16s_12s_27_2_U1->reset(ap_rst);
    qam_dem_top_mul_16s_12s_27_2_U1->din0(grp_fu_276_p0);
    qam_dem_top_mul_16s_12s_27_2_U1->din1(grp_fu_276_p1);
    qam_dem_top_mul_16s_12s_27_2_U1->ce(grp_fu_276_ce);
    qam_dem_top_mul_16s_12s_27_2_U1->dout(grp_fu_276_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_OP1_V_1_fu_692_p1);
    sensitive << ( p_Result_2_fu_644_p5 );

    SC_METHOD(thread_OP1_V_fu_628_p1);
    sensitive << ( p_Result_s_fu_592_p5 );

    SC_METHOD(thread_OP1_V_i_cast_fu_320_p1);
    sensitive << ( din_i_V );

    SC_METHOD(thread_OP2_V_1_fu_697_p1);
    sensitive << ( sd_out_i_V_reg_1491 );

    SC_METHOD(thread_OP2_V_1_i_cast_fu_330_p1);
    sensitive << ( ph_in_q_V );

    SC_METHOD(thread_OP2_V_fu_633_p1);
    sensitive << ( sd_out_q_V_reg_1521 );

    SC_METHOD(thread_OP2_V_i_cast_fu_325_p1);
    sensitive << ( ph_in_i_V );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_ap_sig_bdd_106);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_114);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_122);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_148);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_163);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_176);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_197);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_210);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_221);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_234);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_247);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_275);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_82);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_89);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_99);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_bdd_197 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_bdd_210 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_bdd_221 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_bdd_234 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_bdd_275 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_34 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_82 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_99 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_89 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_106 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_148 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_163 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_176 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_114 );

    SC_METHOD(thread_brmerge1_i_fu_893_p2);
    sensitive << ( overflow_3_reg_1607 );
    sensitive << ( underflow_4_not_i_fu_888_p2 );

    SC_METHOD(thread_brmerge39_i1_i_fu_426_p2);
    sensitive << ( p_not38_i1_i_fu_420_p2 );
    sensitive << ( newsignbit_0_not_i1_i_fu_414_p2 );

    SC_METHOD(thread_brmerge39_i_i1_fu_732_p2);
    sensitive << ( p_not38_i_i1_fu_727_p2 );
    sensitive << ( newsignbit_0_not_i_i1_fu_722_p2 );

    SC_METHOD(thread_brmerge39_i_i_fu_556_p2);
    sensitive << ( p_not38_i_i_fu_551_p2 );
    sensitive << ( newsignbit_0_not_i_i_fu_546_p2 );

    SC_METHOD(thread_brmerge39_i_i_i_fu_872_p2);
    sensitive << ( p_not38_i_i_i_fu_866_p2 );
    sensitive << ( newsignbit_0_not_i_i_i_fu_860_p2 );

    SC_METHOD(thread_brmerge8_i_fu_447_p2);
    sensitive << ( overflow_reg_1503 );
    sensitive << ( underflow_not_i_fu_442_p2 );

    SC_METHOD(thread_brmerge9_i_fu_579_p2);
    sensitive << ( overflow_1_fu_540_p2 );
    sensitive << ( underflow_1_not_i_fu_573_p2 );

    SC_METHOD(thread_brmerge_i1_fu_1115_p2);
    sensitive << ( newsignbit_4_fu_1083_p3 );
    sensitive << ( isneg_not_i_fu_1109_p2 );

    SC_METHOD(thread_brmerge_i1_i_fu_396_p2);
    sensitive << ( newsignbit_fu_372_p3 );
    sensitive << ( p_not_i1_i_fu_390_p2 );

    SC_METHOD(thread_brmerge_i_fu_755_p2);
    sensitive << ( overflow_2_fu_716_p2 );
    sensitive << ( underflow_not_i1_fu_749_p2 );

    SC_METHOD(thread_brmerge_i_i1_fu_706_p2);
    sensitive << ( newsignbit_2_reg_1574 );
    sensitive << ( p_not_i_i9_fu_701_p2 );

    SC_METHOD(thread_brmerge_i_i1_i_fu_438_p2);
    sensitive << ( overflow_reg_1503 );
    sensitive << ( underflow_reg_1509 );

    SC_METHOD(thread_brmerge_i_i4_i_fu_842_p2);
    sensitive << ( newsignbit_3_fu_818_p3 );
    sensitive << ( p_not_i_i_i_fu_836_p2 );

    SC_METHOD(thread_brmerge_i_i_fu_530_p2);
    sensitive << ( newsignbit_1_reg_1533 );
    sensitive << ( p_not_i_i_fu_525_p2 );

    SC_METHOD(thread_brmerge_i_i_i1_fu_743_p2);
    sensitive << ( underflow_2_fu_738_p2 );
    sensitive << ( overflow_2_fu_716_p2 );

    SC_METHOD(thread_brmerge_i_i_i2_fu_1103_p2);
    sensitive << ( newsignbit_4_fu_1083_p3 );
    sensitive << ( isneg_4_fu_1071_p3 );

    SC_METHOD(thread_brmerge_i_i_i_fu_567_p2);
    sensitive << ( underflow_1_fu_562_p2 );
    sensitive << ( overflow_1_fu_540_p2 );

    SC_METHOD(thread_brmerge_i_i_i_i_fu_884_p2);
    sensitive << ( overflow_3_reg_1607 );
    sensitive << ( underflow_3_reg_1613 );

    SC_METHOD(thread_cos_adr_V_3_fu_1283_p2);
    sensitive << ( sin_adr_V_reg_1660 );

    SC_METHOD(thread_cos_adr_V_fu_1288_p3);
    sensitive << ( tmp_26_reg_1654 );
    sensitive << ( sin_adr_V_reg_1660 );
    sensitive << ( cos_adr_V_3_fu_1283_p2 );

    SC_METHOD(thread_cos_lut_address0);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( tmp_23_i_fu_1300_p1 );

    SC_METHOD(thread_cos_lut_address1);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( tmp_24_i_fu_1305_p1 );

    SC_METHOD(thread_cos_lut_ce0);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_cos_lut_ce1);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_dout_mix_i_V);
    sensitive << ( sd_out_i_V_reg_1491 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_dout_mix_i_V_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_dout_mix_q_V);
    sensitive << ( sd_out_q_V_reg_1521 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_dout_mix_q_V_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_grp_fu_276_ce);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_bdd_122 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_grp_fu_276_p0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( OP1_V_i_cast_fu_320_p1 );
    sensitive << ( OP1_V_i_cast_reg_1471 );
    sensitive << ( tmp_1_fu_335_p1 );
    sensitive << ( tmp_1_reg_1486 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( OP2_V_fu_633_p1 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( OP2_V_1_fu_697_p1 );

    SC_METHOD(thread_grp_fu_276_p1);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( OP2_V_i_cast_fu_325_p1 );
    sensitive << ( OP2_V_i_cast_reg_1476 );
    sensitive << ( OP2_V_1_i_cast_fu_330_p1 );
    sensitive << ( OP2_V_1_i_cast_reg_1481 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( OP1_V_fu_628_p1 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( OP1_V_1_fu_692_p1 );

    SC_METHOD(thread_isNeg_1_fu_995_p3);
    sensitive << ( sh_assign_1_fu_989_p2 );

    SC_METHOD(thread_isNeg_2_fu_1160_p3);
    sensitive << ( control_lf_out_gain );

    SC_METHOD(thread_isNeg_fu_927_p3);
    sensitive << ( control_lf_p );

    SC_METHOD(thread_isneg_2_fu_656_p1);
    sensitive << ( grp_fu_276_p2 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_isneg_3_fu_800_p3);
    sensitive << ( p_Val2_23_fu_794_p2 );

    SC_METHOD(thread_isneg_4_fu_1071_p3);
    sensitive << ( p_Val2_27_fu_1065_p2 );

    SC_METHOD(thread_isneg_fu_364_p3);
    sensitive << ( p_Val2_1_fu_348_p2 );

    SC_METHOD(thread_isneg_not_i_fu_1109_p2);
    sensitive << ( isneg_4_fu_1071_p3 );

    SC_METHOD(thread_loop_integ_V);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( p_Val2_41_fu_1145_p3 );
    sensitive << ( loop_integ_V_preg );

    SC_METHOD(thread_loop_integ_V_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_newsignbit_0_not_i1_i_fu_414_p2);
    sensitive << ( newsignbit_fu_372_p3 );

    SC_METHOD(thread_newsignbit_0_not_i_i1_fu_722_p2);
    sensitive << ( newsignbit_2_reg_1574 );

    SC_METHOD(thread_newsignbit_0_not_i_i_fu_546_p2);
    sensitive << ( newsignbit_1_reg_1533 );

    SC_METHOD(thread_newsignbit_0_not_i_i_i_fu_860_p2);
    sensitive << ( newsignbit_3_fu_818_p3 );

    SC_METHOD(thread_newsignbit_2_fu_674_p1);
    sensitive << ( grp_fu_276_p2 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_newsignbit_3_fu_818_p3);
    sensitive << ( p_Val2_23_fu_794_p2 );

    SC_METHOD(thread_newsignbit_4_fu_1083_p3);
    sensitive << ( p_Val2_27_fu_1065_p2 );

    SC_METHOD(thread_newsignbit_fu_372_p3);
    sensitive << ( p_Val2_1_fu_348_p2 );

    SC_METHOD(thread_not_brmerge_i_i1_i_fu_452_p2);
    sensitive << ( brmerge_i_i1_i_fu_438_p2 );

    SC_METHOD(thread_not_brmerge_i_i_i_fu_604_p2);
    sensitive << ( brmerge_i_i_i_fu_567_p2 );

    SC_METHOD(thread_or_cond_fu_1375_p2);
    sensitive << ( sel_tmp7_i_fu_1369_p2 );
    sensitive << ( sel_tmp4_i_fu_1357_p2 );

    SC_METHOD(thread_overflow_1_fu_540_p2);
    sensitive << ( brmerge_i_i_fu_530_p2 );
    sensitive << ( tmp_7_i_fu_535_p2 );

    SC_METHOD(thread_overflow_2_fu_716_p2);
    sensitive << ( brmerge_i_i1_fu_706_p2 );
    sensitive << ( tmp_8_i_fu_711_p2 );

    SC_METHOD(thread_overflow_3_fu_854_p2);
    sensitive << ( brmerge_i_i4_i_fu_842_p2 );
    sensitive << ( tmp_3_i1_fu_848_p2 );

    SC_METHOD(thread_overflow_fu_408_p2);
    sensitive << ( brmerge_i1_i_fu_396_p2 );
    sensitive << ( tmp_5_i_fu_402_p2 );

    SC_METHOD(thread_p_Result_2_fu_644_p5);
    sensitive << ( tmp_1_i3_fu_637_p3 );

    SC_METHOD(thread_p_Result_i8_fu_682_p1);
    sensitive << ( grp_fu_276_p2 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_p_Result_i_fu_380_p4);
    sensitive << ( p_Val2_1_fu_348_p2 );

    SC_METHOD(thread_p_Result_s_fu_592_p5);
    sensitive << ( tmp_i2_fu_585_p3 );

    SC_METHOD(thread_p_Val2_1_fu_348_p2);
    sensitive << ( reg_316 );
    sensitive << ( tmp_6_i_fu_340_p3 );

    SC_METHOD(thread_p_Val2_1_i_fu_905_p3);
    sensitive << ( p_Val2_24_reg_1601 );
    sensitive << ( underflow_3_reg_1613 );

    SC_METHOD(thread_p_Val2_21_mux_i_fu_761_p3);
    sensitive << ( p_Val2_9_reg_1568 );
    sensitive << ( brmerge_i_i_i1_fu_743_p2 );

    SC_METHOD(thread_p_Val2_23_fu_794_p1);
    sensitive << ( reg_316 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_p_Val2_23_fu_794_p2);
    sensitive << ( tmp_10_cast_i_fu_790_p1 );
    sensitive << ( p_Val2_23_fu_794_p1 );

    SC_METHOD(thread_p_Val2_26_fu_977_p3);
    sensitive << ( isNeg_fu_927_p3 );
    sensitive << ( tmp_16_fu_973_p1 );
    sensitive << ( tmp_7_i1_fu_967_p2 );

    SC_METHOD(thread_p_Val2_27_fu_1065_p2);
    sensitive << ( tmp_12_i_fu_1058_p1 );
    sensitive << ( tmp_13_i_fu_1062_p1 );

    SC_METHOD(thread_p_Val2_28_mux_i_fu_1121_p3);
    sensitive << ( brmerge_i_i_i2_fu_1103_p2 );
    sensitive << ( p_Val2_29_fu_1079_p1 );

    SC_METHOD(thread_p_Val2_29_fu_1079_p1);
    sensitive << ( p_Val2_27_fu_1065_p2 );

    SC_METHOD(thread_p_Val2_31_cast_i_fu_1314_p1);
    sensitive << ( cos_lut_q1 );

    SC_METHOD(thread_p_Val2_32_cast_i_fu_1310_p1);
    sensitive << ( cos_lut_q0 );

    SC_METHOD(thread_p_Val2_33_fu_1206_p3);
    sensitive << ( isNeg_2_reg_1636 );
    sensitive << ( tmp_25_fu_1202_p1 );
    sensitive << ( tmp_20_i_fu_1197_p2 );

    SC_METHOD(thread_p_Val2_34_fu_1233_p2);
    sensitive << ( tmp_35_cast_i_fu_1225_p1 );
    sensitive << ( tmp_21_i_fu_1229_p1 );

    SC_METHOD(thread_p_Val2_3_fu_483_p2);
    sensitive << ( reg_316 );
    sensitive << ( tmp_3_i_fu_475_p3 );

    SC_METHOD(thread_p_Val2_41_fu_1145_p3);
    sensitive << ( control_reg_clr );
    sensitive << ( control_reg_init_V );
    sensitive << ( p_Val2_5_fu_1053_p2 );

    SC_METHOD(thread_p_Val2_4_fu_1041_p3);
    sensitive << ( isNeg_1_fu_995_p3 );
    sensitive << ( tmp_18_fu_1037_p1 );
    sensitive << ( tmp_11_i_fu_1031_p2 );

    SC_METHOD(thread_p_Val2_5_fu_1053_p2);
    sensitive << ( i_reg_V );
    sensitive << ( p_Val2_4_reg_1625 );

    SC_METHOD(thread_p_Val2_9_fu_664_p1);
    sensitive << ( grp_fu_276_p2 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_p_Val2_i1_fu_768_p3);
    sensitive << ( p_Val2_9_reg_1568 );
    sensitive << ( underflow_2_fu_738_p2 );

    SC_METHOD(thread_p_Val2_i2_fu_1129_p3);
    sensitive << ( p_Val2_29_fu_1079_p1 );
    sensitive << ( underflow_4_fu_1097_p2 );

    SC_METHOD(thread_p_not38_i1_i_fu_420_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( p_Result_i_fu_380_p4 );

    SC_METHOD(thread_p_not38_i_i1_fu_727_p2);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( p_Result_i8_reg_1580 );

    SC_METHOD(thread_p_not38_i_i_fu_551_p2);
    sensitive << ( p_Result_1_i_reg_1541 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_p_not38_i_i_i_fu_866_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_7_fu_826_p4 );

    SC_METHOD(thread_p_not_i1_i_fu_390_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( p_Result_i_fu_380_p4 );

    SC_METHOD(thread_p_not_i_i9_fu_701_p2);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( p_Result_i8_reg_1580 );

    SC_METHOD(thread_p_not_i_i_fu_525_p2);
    sensitive << ( p_Result_1_i_reg_1541 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_p_not_i_i_i_fu_836_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_7_fu_826_p4 );

    SC_METHOD(thread_ph_out_i_V);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( sel_tmp7_i_fu_1369_p2 );
    sensitive << ( tmp_12_fu_1391_p1 );
    sensitive << ( tmp_28_fu_1405_p3 );

    SC_METHOD(thread_ph_out_i_V_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_ph_out_q_V);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( or_cond_fu_1375_p2 );
    sensitive << ( tmp_32_fu_1446_p3 );
    sensitive << ( tmp_33_fu_1454_p3 );

    SC_METHOD(thread_ph_out_q_V_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_sel_tmp3_demorgan_i_fu_1345_p2);
    sensitive << ( tmp_25_i_fu_1318_p2 );
    sensitive << ( tmp_26_i_fu_1323_p2 );

    SC_METHOD(thread_sel_tmp3_i_fu_1351_p2);
    sensitive << ( sel_tmp3_demorgan_i_fu_1345_p2 );

    SC_METHOD(thread_sel_tmp4_i_fu_1357_p2);
    sensitive << ( tmp_27_i_fu_1328_p2 );
    sensitive << ( sel_tmp3_i_fu_1351_p2 );

    SC_METHOD(thread_sel_tmp6_i_fu_1363_p2);
    sensitive << ( tmp_25_i_fu_1318_p2 );

    SC_METHOD(thread_sel_tmp7_i_fu_1369_p2);
    sensitive << ( tmp_26_i_fu_1323_p2 );
    sensitive << ( sel_tmp6_i_fu_1363_p2 );

    SC_METHOD(thread_sel_tmp_i_fu_1339_p2);
    sensitive << ( p_Val2_32_cast_i_fu_1310_p1 );

    SC_METHOD(thread_sh_assign_1_cast6_i_fu_949_p1);
    sensitive << ( sh_assign_fu_941_p3 );

    SC_METHOD(thread_sh_assign_1_cast_i_fu_953_p1);
    sensitive << ( sh_assign_fu_941_p3 );

    SC_METHOD(thread_sh_assign_1_fu_989_p2);
    sensitive << ( tmp_19_cast_i_fu_985_p1 );

    SC_METHOD(thread_sh_assign_2_fu_1009_p3);
    sensitive << ( sh_assign_1_fu_989_p2 );
    sensitive << ( isNeg_1_fu_995_p3 );
    sensitive << ( tmp_8_i1_fu_1003_p2 );

    SC_METHOD(thread_sh_assign_3_cast5_i_fu_1017_p1);
    sensitive << ( sh_assign_2_fu_1009_p3 );

    SC_METHOD(thread_sh_assign_3_cast_i_fu_1021_p1);
    sensitive << ( sh_assign_2_fu_1009_p3 );

    SC_METHOD(thread_sh_assign_3_fu_1174_p3);
    sensitive << ( control_lf_out_gain );
    sensitive << ( isNeg_2_fu_1160_p3 );
    sensitive << ( tmp_17_i_fu_1168_p2 );

    SC_METHOD(thread_sh_assign_5_cast3_i_fu_1182_p1);
    sensitive << ( sh_assign_3_reg_1641 );

    SC_METHOD(thread_sh_assign_5_cast_i_fu_1185_p1);
    sensitive << ( sh_assign_3_reg_1641 );

    SC_METHOD(thread_sh_assign_fu_941_p3);
    sensitive << ( control_lf_p );
    sensitive << ( isNeg_fu_927_p3 );
    sensitive << ( tmp_4_i_fu_935_p2 );

    SC_METHOD(thread_sin_adr_V_1_fu_1294_p3);
    sensitive << ( tmp_26_reg_1654 );
    sensitive << ( sin_adr_V_reg_1660 );
    sensitive << ( cos_adr_V_3_fu_1283_p2 );

    SC_METHOD(thread_sin_out_V_fu_1333_p2);
    sensitive << ( p_Val2_31_cast_i_fu_1314_p1 );

    SC_METHOD(thread_ssdm_int_V_write_assign_fu_898_p3);
    sensitive << ( p_Val2_24_reg_1601 );
    sensitive << ( brmerge_i_i_i_i_fu_884_p2 );

    SC_METHOD(thread_tmp_10_cast_i_fu_790_p1);
    sensitive << ( tmp_1_i1_fu_783_p3 );

    SC_METHOD(thread_tmp_10_fu_911_p3);
    sensitive << ( brmerge1_i_fu_893_p2 );
    sensitive << ( ssdm_int_V_write_assign_fu_898_p3 );
    sensitive << ( p_Val2_1_i_fu_905_p3 );

    SC_METHOD(thread_tmp_10_i_fu_1025_p2);
    sensitive << ( tmp_5_i1_fu_957_p1 );
    sensitive << ( sh_assign_3_cast_i_fu_1021_p1 );

    SC_METHOD(thread_tmp_11_fu_1381_p4);
    sensitive << ( cos_lut_q0 );

    SC_METHOD(thread_tmp_11_i_fu_1031_p2);
    sensitive << ( tmp_i1_fu_919_p3 );
    sensitive << ( sh_assign_3_cast5_i_fu_1017_p1 );

    SC_METHOD(thread_tmp_12_fu_1391_p1);
    sensitive << ( tmp_11_fu_1381_p4 );

    SC_METHOD(thread_tmp_12_i_fu_1058_p1);
    sensitive << ( p_Val2_5_fu_1053_p2 );

    SC_METHOD(thread_tmp_13_i_fu_1062_p1);
    sensitive << ( p_Val2_26_reg_1620 );

    SC_METHOD(thread_tmp_15_i_fu_1091_p2);
    sensitive << ( newsignbit_4_fu_1083_p3 );

    SC_METHOD(thread_tmp_16_fu_973_p1);
    sensitive << ( tmp_6_i2_fu_961_p2 );

    SC_METHOD(thread_tmp_16_i_fu_1137_p3);
    sensitive << ( brmerge_i1_fu_1115_p2 );
    sensitive << ( p_Val2_28_mux_i_fu_1121_p3 );
    sensitive << ( p_Val2_i2_fu_1129_p3 );

    SC_METHOD(thread_tmp_17_i_fu_1168_p2);
    sensitive << ( control_lf_out_gain );

    SC_METHOD(thread_tmp_18_fu_1037_p1);
    sensitive << ( tmp_10_i_fu_1025_p2 );

    SC_METHOD(thread_tmp_18_i_fu_1188_p1);
    sensitive << ( tmp_16_i_reg_1630 );

    SC_METHOD(thread_tmp_19_cast_i_fu_985_p1);
    sensitive << ( control_lf_i );

    SC_METHOD(thread_tmp_19_i_fu_1191_p2);
    sensitive << ( tmp_18_i_fu_1188_p1 );
    sensitive << ( sh_assign_5_cast_i_fu_1185_p1 );

    SC_METHOD(thread_tmp_1_fu_335_p1);
    sensitive << ( din_q_V );

    SC_METHOD(thread_tmp_1_i1_fu_783_p3);
    sensitive << ( tmp_9_reg_1596 );

    SC_METHOD(thread_tmp_1_i3_fu_637_p3);
    sensitive << ( tmp_6_reg_1547 );

    SC_METHOD(thread_tmp_20_i_fu_1197_p2);
    sensitive << ( tmp_16_i_reg_1630 );
    sensitive << ( sh_assign_5_cast3_i_fu_1182_p1 );

    SC_METHOD(thread_tmp_21_i_fu_1229_p1);
    sensitive << ( p_Val2_33_fu_1206_p3 );

    SC_METHOD(thread_tmp_23_i_fu_1300_p1);
    sensitive << ( cos_adr_V_fu_1288_p3 );

    SC_METHOD(thread_tmp_24_i_fu_1305_p1);
    sensitive << ( sin_adr_V_1_fu_1294_p3 );

    SC_METHOD(thread_tmp_25_fu_1202_p1);
    sensitive << ( tmp_19_i_fu_1191_p2 );

    SC_METHOD(thread_tmp_25_i_fu_1318_p2);
    sensitive << ( msb_V_reg_1647 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_tmp_26_i_fu_1323_p2);
    sensitive << ( msb_V_reg_1647 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_tmp_27_fu_1395_p4);
    sensitive << ( sel_tmp_i_fu_1339_p2 );

    SC_METHOD(thread_tmp_27_i_fu_1328_p2);
    sensitive << ( msb_V_reg_1647 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_tmp_28_fu_1405_p3);
    sensitive << ( sel_tmp4_i_fu_1357_p2 );
    sensitive << ( tmp_12_fu_1391_p1 );
    sensitive << ( tmp_27_fu_1395_p4 );

    SC_METHOD(thread_tmp_29_fu_1422_p4);
    sensitive << ( cos_lut_q1 );

    SC_METHOD(thread_tmp_30_fu_1432_p1);
    sensitive << ( tmp_29_fu_1422_p4 );

    SC_METHOD(thread_tmp_31_fu_1436_p4);
    sensitive << ( sin_out_V_fu_1333_p2 );

    SC_METHOD(thread_tmp_32_fu_1446_p3);
    sensitive << ( sel_tmp7_i_fu_1369_p2 );
    sensitive << ( tmp_30_fu_1432_p1 );
    sensitive << ( tmp_31_fu_1436_p4 );

    SC_METHOD(thread_tmp_33_fu_1454_p3);
    sensitive << ( tmp_25_i_fu_1318_p2 );
    sensitive << ( tmp_30_fu_1432_p1 );
    sensitive << ( tmp_31_fu_1436_p4 );

    SC_METHOD(thread_tmp_35_cast_i_fu_1225_p1);
    sensitive << ( tmp_i2_15_fu_1217_p3 );

    SC_METHOD(thread_tmp_3_fu_467_p3);
    sensitive << ( brmerge8_i_fu_447_p2 );
    sensitive << ( tmp_5_fu_458_p2 );
    sensitive << ( tmp_s_fu_463_p2 );

    SC_METHOD(thread_tmp_3_i1_fu_848_p2);
    sensitive << ( isneg_3_fu_800_p3 );

    SC_METHOD(thread_tmp_3_i_fu_475_p3);
    sensitive << ( reg_312 );

    SC_METHOD(thread_tmp_4_fu_610_p2);
    sensitive << ( newsignbit_1_reg_1533 );
    sensitive << ( not_brmerge_i_i_i_fu_604_p2 );

    SC_METHOD(thread_tmp_4_i_fu_935_p2);
    sensitive << ( control_lf_p );

    SC_METHOD(thread_tmp_5_fu_458_p2);
    sensitive << ( newsignbit_reg_1497 );
    sensitive << ( not_brmerge_i_i1_i_fu_452_p2 );

    SC_METHOD(thread_tmp_5_i1_fu_957_p1);
    sensitive << ( tmp_i1_fu_919_p3 );

    SC_METHOD(thread_tmp_5_i_fu_402_p2);
    sensitive << ( isneg_fu_364_p3 );

    SC_METHOD(thread_tmp_6_fu_620_p3);
    sensitive << ( brmerge9_i_fu_579_p2 );
    sensitive << ( tmp_4_fu_610_p2 );
    sensitive << ( tmp_8_fu_615_p2 );

    SC_METHOD(thread_tmp_6_i2_fu_961_p2);
    sensitive << ( tmp_5_i1_fu_957_p1 );
    sensitive << ( sh_assign_1_cast_i_fu_953_p1 );

    SC_METHOD(thread_tmp_6_i_fu_340_p3);
    sensitive << ( reg_312 );

    SC_METHOD(thread_tmp_7_fu_826_p4);
    sensitive << ( p_Val2_23_fu_794_p2 );

    SC_METHOD(thread_tmp_7_i1_fu_967_p2);
    sensitive << ( tmp_i1_fu_919_p3 );
    sensitive << ( sh_assign_1_cast6_i_fu_949_p1 );

    SC_METHOD(thread_tmp_7_i_fu_535_p2);
    sensitive << ( isneg_1_reg_1527 );

    SC_METHOD(thread_tmp_8_fu_615_p2);
    sensitive << ( newsignbit_1_reg_1533 );
    sensitive << ( underflow_1_fu_562_p2 );

    SC_METHOD(thread_tmp_8_i1_fu_1003_p2);
    sensitive << ( tmp_19_cast_i_fu_985_p1 );

    SC_METHOD(thread_tmp_8_i_fu_711_p2);
    sensitive << ( isneg_2_reg_1562 );

    SC_METHOD(thread_tmp_9_fu_775_p3);
    sensitive << ( brmerge_i_fu_755_p2 );
    sensitive << ( p_Val2_21_mux_i_fu_761_p3 );
    sensitive << ( p_Val2_i1_fu_768_p3 );

    SC_METHOD(thread_tmp_i1_fu_919_p3);
    sensitive << ( tmp_10_fu_911_p3 );

    SC_METHOD(thread_tmp_i2_15_fu_1217_p3);
    sensitive << ( phase_angle_V );

    SC_METHOD(thread_tmp_i2_fu_585_p3);
    sensitive << ( tmp_3_reg_1516 );

    SC_METHOD(thread_tmp_s_fu_463_p2);
    sensitive << ( newsignbit_reg_1497 );
    sensitive << ( underflow_reg_1509 );

    SC_METHOD(thread_underflow_1_fu_562_p2);
    sensitive << ( isneg_1_reg_1527 );
    sensitive << ( brmerge39_i_i_fu_556_p2 );

    SC_METHOD(thread_underflow_1_not_i_fu_573_p2);
    sensitive << ( underflow_1_fu_562_p2 );

    SC_METHOD(thread_underflow_2_fu_738_p2);
    sensitive << ( isneg_2_reg_1562 );
    sensitive << ( brmerge39_i_i1_fu_732_p2 );

    SC_METHOD(thread_underflow_3_fu_878_p2);
    sensitive << ( isneg_3_fu_800_p3 );
    sensitive << ( brmerge39_i_i_i_fu_872_p2 );

    SC_METHOD(thread_underflow_4_fu_1097_p2);
    sensitive << ( isneg_4_fu_1071_p3 );
    sensitive << ( tmp_15_i_fu_1091_p2 );

    SC_METHOD(thread_underflow_4_not_i_fu_888_p2);
    sensitive << ( underflow_3_reg_1613 );

    SC_METHOD(thread_underflow_fu_432_p2);
    sensitive << ( isneg_fu_364_p3 );
    sensitive << ( brmerge39_i1_i_fu_426_p2 );

    SC_METHOD(thread_underflow_not_i1_fu_749_p2);
    sensitive << ( underflow_2_fu_738_p2 );

    SC_METHOD(thread_underflow_not_i_fu_442_p2);
    sensitive << ( underflow_reg_1509 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_122 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000000000001";
    i_reg_V = "0000000000000000000000000000";
    phase_angle_V = "0000000000000000";
    loop_integ_V_preg = "0000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "qam_dem_top_mounstrito_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, din_i_V, "(port)din_i_V");
    sc_trace(mVcdFile, din_q_V, "(port)din_q_V");
    sc_trace(mVcdFile, dout_mix_i_V, "(port)dout_mix_i_V");
    sc_trace(mVcdFile, dout_mix_i_V_ap_vld, "(port)dout_mix_i_V_ap_vld");
    sc_trace(mVcdFile, dout_mix_q_V, "(port)dout_mix_q_V");
    sc_trace(mVcdFile, dout_mix_q_V_ap_vld, "(port)dout_mix_q_V_ap_vld");
    sc_trace(mVcdFile, ph_in_i_V, "(port)ph_in_i_V");
    sc_trace(mVcdFile, ph_in_q_V, "(port)ph_in_q_V");
    sc_trace(mVcdFile, ph_out_i_V, "(port)ph_out_i_V");
    sc_trace(mVcdFile, ph_out_i_V_ap_vld, "(port)ph_out_i_V_ap_vld");
    sc_trace(mVcdFile, ph_out_q_V, "(port)ph_out_q_V");
    sc_trace(mVcdFile, ph_out_q_V_ap_vld, "(port)ph_out_q_V_ap_vld");
    sc_trace(mVcdFile, loop_integ_V, "(port)loop_integ_V");
    sc_trace(mVcdFile, loop_integ_V_ap_vld, "(port)loop_integ_V_ap_vld");
    sc_trace(mVcdFile, control_lf_p, "(port)control_lf_p");
    sc_trace(mVcdFile, control_lf_i, "(port)control_lf_i");
    sc_trace(mVcdFile, control_lf_out_gain, "(port)control_lf_out_gain");
    sc_trace(mVcdFile, control_reg_clr, "(port)control_reg_clr");
    sc_trace(mVcdFile, control_reg_init_V, "(port)control_reg_init_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_34, "ap_sig_bdd_34");
    sc_trace(mVcdFile, i_reg_V, "i_reg_V");
    sc_trace(mVcdFile, phase_angle_V, "phase_angle_V");
    sc_trace(mVcdFile, cos_lut_address0, "cos_lut_address0");
    sc_trace(mVcdFile, cos_lut_ce0, "cos_lut_ce0");
    sc_trace(mVcdFile, cos_lut_q0, "cos_lut_q0");
    sc_trace(mVcdFile, cos_lut_address1, "cos_lut_address1");
    sc_trace(mVcdFile, cos_lut_ce1, "cos_lut_ce1");
    sc_trace(mVcdFile, cos_lut_q1, "cos_lut_q1");
    sc_trace(mVcdFile, reg_312, "reg_312");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_82, "ap_sig_bdd_82");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_89, "ap_sig_bdd_89");
    sc_trace(mVcdFile, grp_fu_276_p2, "grp_fu_276_p2");
    sc_trace(mVcdFile, reg_316, "reg_316");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_99, "ap_sig_bdd_99");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_106, "ap_sig_bdd_106");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_114, "ap_sig_bdd_114");
    sc_trace(mVcdFile, OP1_V_i_cast_fu_320_p1, "OP1_V_i_cast_fu_320_p1");
    sc_trace(mVcdFile, OP1_V_i_cast_reg_1471, "OP1_V_i_cast_reg_1471");
    sc_trace(mVcdFile, ap_sig_bdd_122, "ap_sig_bdd_122");
    sc_trace(mVcdFile, OP2_V_i_cast_fu_325_p1, "OP2_V_i_cast_fu_325_p1");
    sc_trace(mVcdFile, OP2_V_i_cast_reg_1476, "OP2_V_i_cast_reg_1476");
    sc_trace(mVcdFile, OP2_V_1_i_cast_fu_330_p1, "OP2_V_1_i_cast_fu_330_p1");
    sc_trace(mVcdFile, OP2_V_1_i_cast_reg_1481, "OP2_V_1_i_cast_reg_1481");
    sc_trace(mVcdFile, tmp_1_fu_335_p1, "tmp_1_fu_335_p1");
    sc_trace(mVcdFile, tmp_1_reg_1486, "tmp_1_reg_1486");
    sc_trace(mVcdFile, sd_out_i_V_reg_1491, "sd_out_i_V_reg_1491");
    sc_trace(mVcdFile, newsignbit_fu_372_p3, "newsignbit_fu_372_p3");
    sc_trace(mVcdFile, newsignbit_reg_1497, "newsignbit_reg_1497");
    sc_trace(mVcdFile, overflow_fu_408_p2, "overflow_fu_408_p2");
    sc_trace(mVcdFile, overflow_reg_1503, "overflow_reg_1503");
    sc_trace(mVcdFile, underflow_fu_432_p2, "underflow_fu_432_p2");
    sc_trace(mVcdFile, underflow_reg_1509, "underflow_reg_1509");
    sc_trace(mVcdFile, tmp_3_fu_467_p3, "tmp_3_fu_467_p3");
    sc_trace(mVcdFile, tmp_3_reg_1516, "tmp_3_reg_1516");
    sc_trace(mVcdFile, sd_out_q_V_reg_1521, "sd_out_q_V_reg_1521");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_148, "ap_sig_bdd_148");
    sc_trace(mVcdFile, isneg_1_reg_1527, "isneg_1_reg_1527");
    sc_trace(mVcdFile, newsignbit_1_reg_1533, "newsignbit_1_reg_1533");
    sc_trace(mVcdFile, p_Result_1_i_reg_1541, "p_Result_1_i_reg_1541");
    sc_trace(mVcdFile, tmp_6_fu_620_p3, "tmp_6_fu_620_p3");
    sc_trace(mVcdFile, tmp_6_reg_1547, "tmp_6_reg_1547");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_163, "ap_sig_bdd_163");
    sc_trace(mVcdFile, OP1_V_fu_628_p1, "OP1_V_fu_628_p1");
    sc_trace(mVcdFile, OP2_V_fu_633_p1, "OP2_V_fu_633_p1");
    sc_trace(mVcdFile, isneg_2_reg_1562, "isneg_2_reg_1562");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_176, "ap_sig_bdd_176");
    sc_trace(mVcdFile, p_Val2_9_reg_1568, "p_Val2_9_reg_1568");
    sc_trace(mVcdFile, newsignbit_2_reg_1574, "newsignbit_2_reg_1574");
    sc_trace(mVcdFile, p_Result_i8_reg_1580, "p_Result_i8_reg_1580");
    sc_trace(mVcdFile, OP1_V_1_fu_692_p1, "OP1_V_1_fu_692_p1");
    sc_trace(mVcdFile, OP2_V_1_fu_697_p1, "OP2_V_1_fu_697_p1");
    sc_trace(mVcdFile, tmp_9_fu_775_p3, "tmp_9_fu_775_p3");
    sc_trace(mVcdFile, tmp_9_reg_1596, "tmp_9_reg_1596");
    sc_trace(mVcdFile, p_Val2_24_reg_1601, "p_Val2_24_reg_1601");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_bdd_197, "ap_sig_bdd_197");
    sc_trace(mVcdFile, overflow_3_fu_854_p2, "overflow_3_fu_854_p2");
    sc_trace(mVcdFile, overflow_3_reg_1607, "overflow_3_reg_1607");
    sc_trace(mVcdFile, underflow_3_fu_878_p2, "underflow_3_fu_878_p2");
    sc_trace(mVcdFile, underflow_3_reg_1613, "underflow_3_reg_1613");
    sc_trace(mVcdFile, p_Val2_26_fu_977_p3, "p_Val2_26_fu_977_p3");
    sc_trace(mVcdFile, p_Val2_26_reg_1620, "p_Val2_26_reg_1620");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_bdd_210, "ap_sig_bdd_210");
    sc_trace(mVcdFile, p_Val2_4_fu_1041_p3, "p_Val2_4_fu_1041_p3");
    sc_trace(mVcdFile, p_Val2_4_reg_1625, "p_Val2_4_reg_1625");
    sc_trace(mVcdFile, tmp_16_i_fu_1137_p3, "tmp_16_i_fu_1137_p3");
    sc_trace(mVcdFile, tmp_16_i_reg_1630, "tmp_16_i_reg_1630");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_bdd_221, "ap_sig_bdd_221");
    sc_trace(mVcdFile, isNeg_2_fu_1160_p3, "isNeg_2_fu_1160_p3");
    sc_trace(mVcdFile, isNeg_2_reg_1636, "isNeg_2_reg_1636");
    sc_trace(mVcdFile, sh_assign_3_fu_1174_p3, "sh_assign_3_fu_1174_p3");
    sc_trace(mVcdFile, sh_assign_3_reg_1641, "sh_assign_3_reg_1641");
    sc_trace(mVcdFile, msb_V_reg_1647, "msb_V_reg_1647");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_bdd_234, "ap_sig_bdd_234");
    sc_trace(mVcdFile, tmp_26_reg_1654, "tmp_26_reg_1654");
    sc_trace(mVcdFile, sin_adr_V_reg_1660, "sin_adr_V_reg_1660");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_bdd_247, "ap_sig_bdd_247");
    sc_trace(mVcdFile, tmp_23_i_fu_1300_p1, "tmp_23_i_fu_1300_p1");
    sc_trace(mVcdFile, tmp_24_i_fu_1305_p1, "tmp_24_i_fu_1305_p1");
    sc_trace(mVcdFile, p_Val2_41_fu_1145_p3, "p_Val2_41_fu_1145_p3");
    sc_trace(mVcdFile, loop_integ_V_preg, "loop_integ_V_preg");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_bdd_275, "ap_sig_bdd_275");
    sc_trace(mVcdFile, grp_fu_276_p0, "grp_fu_276_p0");
    sc_trace(mVcdFile, grp_fu_276_p1, "grp_fu_276_p1");
    sc_trace(mVcdFile, tmp_6_i_fu_340_p3, "tmp_6_i_fu_340_p3");
    sc_trace(mVcdFile, p_Val2_1_fu_348_p2, "p_Val2_1_fu_348_p2");
    sc_trace(mVcdFile, p_Result_i_fu_380_p4, "p_Result_i_fu_380_p4");
    sc_trace(mVcdFile, p_not_i1_i_fu_390_p2, "p_not_i1_i_fu_390_p2");
    sc_trace(mVcdFile, isneg_fu_364_p3, "isneg_fu_364_p3");
    sc_trace(mVcdFile, brmerge_i1_i_fu_396_p2, "brmerge_i1_i_fu_396_p2");
    sc_trace(mVcdFile, tmp_5_i_fu_402_p2, "tmp_5_i_fu_402_p2");
    sc_trace(mVcdFile, p_not38_i1_i_fu_420_p2, "p_not38_i1_i_fu_420_p2");
    sc_trace(mVcdFile, newsignbit_0_not_i1_i_fu_414_p2, "newsignbit_0_not_i1_i_fu_414_p2");
    sc_trace(mVcdFile, brmerge39_i1_i_fu_426_p2, "brmerge39_i1_i_fu_426_p2");
    sc_trace(mVcdFile, underflow_not_i_fu_442_p2, "underflow_not_i_fu_442_p2");
    sc_trace(mVcdFile, brmerge_i_i1_i_fu_438_p2, "brmerge_i_i1_i_fu_438_p2");
    sc_trace(mVcdFile, not_brmerge_i_i1_i_fu_452_p2, "not_brmerge_i_i1_i_fu_452_p2");
    sc_trace(mVcdFile, brmerge8_i_fu_447_p2, "brmerge8_i_fu_447_p2");
    sc_trace(mVcdFile, tmp_5_fu_458_p2, "tmp_5_fu_458_p2");
    sc_trace(mVcdFile, tmp_s_fu_463_p2, "tmp_s_fu_463_p2");
    sc_trace(mVcdFile, tmp_3_i_fu_475_p3, "tmp_3_i_fu_475_p3");
    sc_trace(mVcdFile, p_Val2_3_fu_483_p2, "p_Val2_3_fu_483_p2");
    sc_trace(mVcdFile, p_not_i_i_fu_525_p2, "p_not_i_i_fu_525_p2");
    sc_trace(mVcdFile, brmerge_i_i_fu_530_p2, "brmerge_i_i_fu_530_p2");
    sc_trace(mVcdFile, tmp_7_i_fu_535_p2, "tmp_7_i_fu_535_p2");
    sc_trace(mVcdFile, p_not38_i_i_fu_551_p2, "p_not38_i_i_fu_551_p2");
    sc_trace(mVcdFile, newsignbit_0_not_i_i_fu_546_p2, "newsignbit_0_not_i_i_fu_546_p2");
    sc_trace(mVcdFile, brmerge39_i_i_fu_556_p2, "brmerge39_i_i_fu_556_p2");
    sc_trace(mVcdFile, underflow_1_fu_562_p2, "underflow_1_fu_562_p2");
    sc_trace(mVcdFile, overflow_1_fu_540_p2, "overflow_1_fu_540_p2");
    sc_trace(mVcdFile, underflow_1_not_i_fu_573_p2, "underflow_1_not_i_fu_573_p2");
    sc_trace(mVcdFile, tmp_i2_fu_585_p3, "tmp_i2_fu_585_p3");
    sc_trace(mVcdFile, brmerge_i_i_i_fu_567_p2, "brmerge_i_i_i_fu_567_p2");
    sc_trace(mVcdFile, not_brmerge_i_i_i_fu_604_p2, "not_brmerge_i_i_i_fu_604_p2");
    sc_trace(mVcdFile, brmerge9_i_fu_579_p2, "brmerge9_i_fu_579_p2");
    sc_trace(mVcdFile, tmp_4_fu_610_p2, "tmp_4_fu_610_p2");
    sc_trace(mVcdFile, tmp_8_fu_615_p2, "tmp_8_fu_615_p2");
    sc_trace(mVcdFile, p_Result_s_fu_592_p5, "p_Result_s_fu_592_p5");
    sc_trace(mVcdFile, tmp_1_i3_fu_637_p3, "tmp_1_i3_fu_637_p3");
    sc_trace(mVcdFile, isneg_2_fu_656_p1, "isneg_2_fu_656_p1");
    sc_trace(mVcdFile, p_Val2_9_fu_664_p1, "p_Val2_9_fu_664_p1");
    sc_trace(mVcdFile, newsignbit_2_fu_674_p1, "newsignbit_2_fu_674_p1");
    sc_trace(mVcdFile, p_Result_i8_fu_682_p1, "p_Result_i8_fu_682_p1");
    sc_trace(mVcdFile, p_Result_2_fu_644_p5, "p_Result_2_fu_644_p5");
    sc_trace(mVcdFile, p_not_i_i9_fu_701_p2, "p_not_i_i9_fu_701_p2");
    sc_trace(mVcdFile, brmerge_i_i1_fu_706_p2, "brmerge_i_i1_fu_706_p2");
    sc_trace(mVcdFile, tmp_8_i_fu_711_p2, "tmp_8_i_fu_711_p2");
    sc_trace(mVcdFile, p_not38_i_i1_fu_727_p2, "p_not38_i_i1_fu_727_p2");
    sc_trace(mVcdFile, newsignbit_0_not_i_i1_fu_722_p2, "newsignbit_0_not_i_i1_fu_722_p2");
    sc_trace(mVcdFile, brmerge39_i_i1_fu_732_p2, "brmerge39_i_i1_fu_732_p2");
    sc_trace(mVcdFile, underflow_2_fu_738_p2, "underflow_2_fu_738_p2");
    sc_trace(mVcdFile, overflow_2_fu_716_p2, "overflow_2_fu_716_p2");
    sc_trace(mVcdFile, underflow_not_i1_fu_749_p2, "underflow_not_i1_fu_749_p2");
    sc_trace(mVcdFile, brmerge_i_i_i1_fu_743_p2, "brmerge_i_i_i1_fu_743_p2");
    sc_trace(mVcdFile, brmerge_i_fu_755_p2, "brmerge_i_fu_755_p2");
    sc_trace(mVcdFile, p_Val2_21_mux_i_fu_761_p3, "p_Val2_21_mux_i_fu_761_p3");
    sc_trace(mVcdFile, p_Val2_i1_fu_768_p3, "p_Val2_i1_fu_768_p3");
    sc_trace(mVcdFile, tmp_1_i1_fu_783_p3, "tmp_1_i1_fu_783_p3");
    sc_trace(mVcdFile, tmp_10_cast_i_fu_790_p1, "tmp_10_cast_i_fu_790_p1");
    sc_trace(mVcdFile, p_Val2_23_fu_794_p1, "p_Val2_23_fu_794_p1");
    sc_trace(mVcdFile, p_Val2_23_fu_794_p2, "p_Val2_23_fu_794_p2");
    sc_trace(mVcdFile, tmp_7_fu_826_p4, "tmp_7_fu_826_p4");
    sc_trace(mVcdFile, newsignbit_3_fu_818_p3, "newsignbit_3_fu_818_p3");
    sc_trace(mVcdFile, p_not_i_i_i_fu_836_p2, "p_not_i_i_i_fu_836_p2");
    sc_trace(mVcdFile, isneg_3_fu_800_p3, "isneg_3_fu_800_p3");
    sc_trace(mVcdFile, brmerge_i_i4_i_fu_842_p2, "brmerge_i_i4_i_fu_842_p2");
    sc_trace(mVcdFile, tmp_3_i1_fu_848_p2, "tmp_3_i1_fu_848_p2");
    sc_trace(mVcdFile, p_not38_i_i_i_fu_866_p2, "p_not38_i_i_i_fu_866_p2");
    sc_trace(mVcdFile, newsignbit_0_not_i_i_i_fu_860_p2, "newsignbit_0_not_i_i_i_fu_860_p2");
    sc_trace(mVcdFile, brmerge39_i_i_i_fu_872_p2, "brmerge39_i_i_i_fu_872_p2");
    sc_trace(mVcdFile, underflow_4_not_i_fu_888_p2, "underflow_4_not_i_fu_888_p2");
    sc_trace(mVcdFile, brmerge_i_i_i_i_fu_884_p2, "brmerge_i_i_i_i_fu_884_p2");
    sc_trace(mVcdFile, brmerge1_i_fu_893_p2, "brmerge1_i_fu_893_p2");
    sc_trace(mVcdFile, ssdm_int_V_write_assign_fu_898_p3, "ssdm_int_V_write_assign_fu_898_p3");
    sc_trace(mVcdFile, p_Val2_1_i_fu_905_p3, "p_Val2_1_i_fu_905_p3");
    sc_trace(mVcdFile, tmp_10_fu_911_p3, "tmp_10_fu_911_p3");
    sc_trace(mVcdFile, isNeg_fu_927_p3, "isNeg_fu_927_p3");
    sc_trace(mVcdFile, tmp_4_i_fu_935_p2, "tmp_4_i_fu_935_p2");
    sc_trace(mVcdFile, sh_assign_fu_941_p3, "sh_assign_fu_941_p3");
    sc_trace(mVcdFile, tmp_i1_fu_919_p3, "tmp_i1_fu_919_p3");
    sc_trace(mVcdFile, tmp_5_i1_fu_957_p1, "tmp_5_i1_fu_957_p1");
    sc_trace(mVcdFile, sh_assign_1_cast_i_fu_953_p1, "sh_assign_1_cast_i_fu_953_p1");
    sc_trace(mVcdFile, sh_assign_1_cast6_i_fu_949_p1, "sh_assign_1_cast6_i_fu_949_p1");
    sc_trace(mVcdFile, tmp_6_i2_fu_961_p2, "tmp_6_i2_fu_961_p2");
    sc_trace(mVcdFile, tmp_16_fu_973_p1, "tmp_16_fu_973_p1");
    sc_trace(mVcdFile, tmp_7_i1_fu_967_p2, "tmp_7_i1_fu_967_p2");
    sc_trace(mVcdFile, tmp_19_cast_i_fu_985_p1, "tmp_19_cast_i_fu_985_p1");
    sc_trace(mVcdFile, sh_assign_1_fu_989_p2, "sh_assign_1_fu_989_p2");
    sc_trace(mVcdFile, isNeg_1_fu_995_p3, "isNeg_1_fu_995_p3");
    sc_trace(mVcdFile, tmp_8_i1_fu_1003_p2, "tmp_8_i1_fu_1003_p2");
    sc_trace(mVcdFile, sh_assign_2_fu_1009_p3, "sh_assign_2_fu_1009_p3");
    sc_trace(mVcdFile, sh_assign_3_cast_i_fu_1021_p1, "sh_assign_3_cast_i_fu_1021_p1");
    sc_trace(mVcdFile, sh_assign_3_cast5_i_fu_1017_p1, "sh_assign_3_cast5_i_fu_1017_p1");
    sc_trace(mVcdFile, tmp_10_i_fu_1025_p2, "tmp_10_i_fu_1025_p2");
    sc_trace(mVcdFile, tmp_18_fu_1037_p1, "tmp_18_fu_1037_p1");
    sc_trace(mVcdFile, tmp_11_i_fu_1031_p2, "tmp_11_i_fu_1031_p2");
    sc_trace(mVcdFile, p_Val2_5_fu_1053_p2, "p_Val2_5_fu_1053_p2");
    sc_trace(mVcdFile, tmp_12_i_fu_1058_p1, "tmp_12_i_fu_1058_p1");
    sc_trace(mVcdFile, tmp_13_i_fu_1062_p1, "tmp_13_i_fu_1062_p1");
    sc_trace(mVcdFile, p_Val2_27_fu_1065_p2, "p_Val2_27_fu_1065_p2");
    sc_trace(mVcdFile, newsignbit_4_fu_1083_p3, "newsignbit_4_fu_1083_p3");
    sc_trace(mVcdFile, isneg_4_fu_1071_p3, "isneg_4_fu_1071_p3");
    sc_trace(mVcdFile, tmp_15_i_fu_1091_p2, "tmp_15_i_fu_1091_p2");
    sc_trace(mVcdFile, isneg_not_i_fu_1109_p2, "isneg_not_i_fu_1109_p2");
    sc_trace(mVcdFile, brmerge_i_i_i2_fu_1103_p2, "brmerge_i_i_i2_fu_1103_p2");
    sc_trace(mVcdFile, p_Val2_29_fu_1079_p1, "p_Val2_29_fu_1079_p1");
    sc_trace(mVcdFile, underflow_4_fu_1097_p2, "underflow_4_fu_1097_p2");
    sc_trace(mVcdFile, brmerge_i1_fu_1115_p2, "brmerge_i1_fu_1115_p2");
    sc_trace(mVcdFile, p_Val2_28_mux_i_fu_1121_p3, "p_Val2_28_mux_i_fu_1121_p3");
    sc_trace(mVcdFile, p_Val2_i2_fu_1129_p3, "p_Val2_i2_fu_1129_p3");
    sc_trace(mVcdFile, tmp_17_i_fu_1168_p2, "tmp_17_i_fu_1168_p2");
    sc_trace(mVcdFile, tmp_18_i_fu_1188_p1, "tmp_18_i_fu_1188_p1");
    sc_trace(mVcdFile, sh_assign_5_cast_i_fu_1185_p1, "sh_assign_5_cast_i_fu_1185_p1");
    sc_trace(mVcdFile, sh_assign_5_cast3_i_fu_1182_p1, "sh_assign_5_cast3_i_fu_1182_p1");
    sc_trace(mVcdFile, tmp_19_i_fu_1191_p2, "tmp_19_i_fu_1191_p2");
    sc_trace(mVcdFile, tmp_25_fu_1202_p1, "tmp_25_fu_1202_p1");
    sc_trace(mVcdFile, tmp_20_i_fu_1197_p2, "tmp_20_i_fu_1197_p2");
    sc_trace(mVcdFile, tmp_i2_15_fu_1217_p3, "tmp_i2_15_fu_1217_p3");
    sc_trace(mVcdFile, p_Val2_33_fu_1206_p3, "p_Val2_33_fu_1206_p3");
    sc_trace(mVcdFile, tmp_35_cast_i_fu_1225_p1, "tmp_35_cast_i_fu_1225_p1");
    sc_trace(mVcdFile, tmp_21_i_fu_1229_p1, "tmp_21_i_fu_1229_p1");
    sc_trace(mVcdFile, p_Val2_34_fu_1233_p2, "p_Val2_34_fu_1233_p2");
    sc_trace(mVcdFile, cos_adr_V_3_fu_1283_p2, "cos_adr_V_3_fu_1283_p2");
    sc_trace(mVcdFile, cos_adr_V_fu_1288_p3, "cos_adr_V_fu_1288_p3");
    sc_trace(mVcdFile, sin_adr_V_1_fu_1294_p3, "sin_adr_V_1_fu_1294_p3");
    sc_trace(mVcdFile, p_Val2_31_cast_i_fu_1314_p1, "p_Val2_31_cast_i_fu_1314_p1");
    sc_trace(mVcdFile, p_Val2_32_cast_i_fu_1310_p1, "p_Val2_32_cast_i_fu_1310_p1");
    sc_trace(mVcdFile, tmp_25_i_fu_1318_p2, "tmp_25_i_fu_1318_p2");
    sc_trace(mVcdFile, tmp_26_i_fu_1323_p2, "tmp_26_i_fu_1323_p2");
    sc_trace(mVcdFile, sel_tmp3_demorgan_i_fu_1345_p2, "sel_tmp3_demorgan_i_fu_1345_p2");
    sc_trace(mVcdFile, tmp_27_i_fu_1328_p2, "tmp_27_i_fu_1328_p2");
    sc_trace(mVcdFile, sel_tmp3_i_fu_1351_p2, "sel_tmp3_i_fu_1351_p2");
    sc_trace(mVcdFile, sel_tmp6_i_fu_1363_p2, "sel_tmp6_i_fu_1363_p2");
    sc_trace(mVcdFile, sel_tmp7_i_fu_1369_p2, "sel_tmp7_i_fu_1369_p2");
    sc_trace(mVcdFile, sel_tmp4_i_fu_1357_p2, "sel_tmp4_i_fu_1357_p2");
    sc_trace(mVcdFile, tmp_11_fu_1381_p4, "tmp_11_fu_1381_p4");
    sc_trace(mVcdFile, sel_tmp_i_fu_1339_p2, "sel_tmp_i_fu_1339_p2");
    sc_trace(mVcdFile, tmp_12_fu_1391_p1, "tmp_12_fu_1391_p1");
    sc_trace(mVcdFile, tmp_27_fu_1395_p4, "tmp_27_fu_1395_p4");
    sc_trace(mVcdFile, tmp_28_fu_1405_p3, "tmp_28_fu_1405_p3");
    sc_trace(mVcdFile, tmp_29_fu_1422_p4, "tmp_29_fu_1422_p4");
    sc_trace(mVcdFile, sin_out_V_fu_1333_p2, "sin_out_V_fu_1333_p2");
    sc_trace(mVcdFile, tmp_30_fu_1432_p1, "tmp_30_fu_1432_p1");
    sc_trace(mVcdFile, tmp_31_fu_1436_p4, "tmp_31_fu_1436_p4");
    sc_trace(mVcdFile, or_cond_fu_1375_p2, "or_cond_fu_1375_p2");
    sc_trace(mVcdFile, tmp_32_fu_1446_p3, "tmp_32_fu_1446_p3");
    sc_trace(mVcdFile, tmp_33_fu_1454_p3, "tmp_33_fu_1454_p3");
    sc_trace(mVcdFile, grp_fu_276_ce, "grp_fu_276_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

qam_dem_top_mounstrito::~qam_dem_top_mounstrito() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete cos_lut_U;
    delete qam_dem_top_mul_16s_12s_27_2_U1;
}

void qam_dem_top_mounstrito::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        loop_integ_V_preg = ap_const_lv28_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
            loop_integ_V_preg = p_Val2_41_fu_1145_p3.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !ap_sig_bdd_122.read())) {
        OP1_V_i_cast_reg_1471 = OP1_V_i_cast_fu_320_p1.read();
        OP2_V_i_cast_reg_1476 = OP2_V_i_cast_fu_325_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        OP2_V_1_i_cast_reg_1481 = OP2_V_1_i_cast_fu_330_p1.read();
        tmp_1_reg_1486 = tmp_1_fu_335_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        i_reg_V = p_Val2_41_fu_1145_p3.read();
        isNeg_2_reg_1636 = control_lf_out_gain.read().range(7, 7);
        sh_assign_3_reg_1641 = sh_assign_3_fu_1174_p3.read();
        tmp_16_i_reg_1630 = tmp_16_i_fu_1137_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        isneg_1_reg_1527 = p_Val2_3_fu_483_p2.read().range(26, 26);
        newsignbit_1_reg_1533 = p_Val2_3_fu_483_p2.read().range(24, 24);
        p_Result_1_i_reg_1541 = p_Val2_3_fu_483_p2.read().range(26, 25);
        sd_out_q_V_reg_1521 = p_Val2_3_fu_483_p2.read().range(26, 11);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        isneg_2_reg_1562 = isneg_2_fu_656_p1.read().range(20, 20);
        newsignbit_2_reg_1574 = newsignbit_2_fu_674_p1.read().range(18, 18);
        p_Result_i8_reg_1580 = p_Result_i8_fu_682_p1.read().range(20, 19);
        p_Val2_9_reg_1568 = p_Val2_9_fu_664_p1.read().range(18, 5);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        msb_V_reg_1647 = p_Val2_34_fu_1233_p2.read().range(26, 25);
        phase_angle_V = p_Val2_34_fu_1233_p2.read().range(26, 11);
        sin_adr_V_reg_1660 = p_Val2_34_fu_1233_p2.read().range(24, 15);
        tmp_26_reg_1654 = p_Val2_34_fu_1233_p2.read().range(25, 25);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        newsignbit_reg_1497 = p_Val2_1_fu_348_p2.read().range(24, 24);
        overflow_reg_1503 = overflow_fu_408_p2.read();
        sd_out_i_V_reg_1491 = p_Val2_1_fu_348_p2.read().range(26, 11);
        underflow_reg_1509 = underflow_fu_432_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        overflow_3_reg_1607 = overflow_3_fu_854_p2.read();
        p_Val2_24_reg_1601 = p_Val2_23_fu_794_p2.read().range(18, 5);
        underflow_3_reg_1613 = underflow_3_fu_878_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        p_Val2_26_reg_1620 = p_Val2_26_fu_977_p3.read();
        p_Val2_4_reg_1625 = p_Val2_4_fu_1041_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        reg_312 = grp_fu_276_p2.read().range(26, 11);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()))) {
        reg_316 = grp_fu_276_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        tmp_3_reg_1516 = tmp_3_fu_467_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        tmp_6_reg_1547 = tmp_6_fu_620_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        tmp_9_reg_1596 = tmp_9_fu_775_p3.read();
    }
}

void qam_dem_top_mounstrito::thread_OP1_V_1_fu_692_p1() {
    OP1_V_1_fu_692_p1 = esl_sext<21,5>(p_Result_2_fu_644_p5.read());
}

void qam_dem_top_mounstrito::thread_OP1_V_fu_628_p1() {
    OP1_V_fu_628_p1 = esl_sext<21,5>(p_Result_s_fu_592_p5.read());
}

void qam_dem_top_mounstrito::thread_OP1_V_i_cast_fu_320_p1() {
    OP1_V_i_cast_fu_320_p1 = esl_sext<27,16>(din_i_V.read());
}

void qam_dem_top_mounstrito::thread_OP2_V_1_fu_697_p1() {
    OP2_V_1_fu_697_p1 = esl_sext<21,16>(sd_out_i_V_reg_1491.read());
}

void qam_dem_top_mounstrito::thread_OP2_V_1_i_cast_fu_330_p1() {
    OP2_V_1_i_cast_fu_330_p1 = esl_sext<27,12>(ph_in_q_V.read());
}

void qam_dem_top_mounstrito::thread_OP2_V_fu_633_p1() {
    OP2_V_fu_633_p1 = esl_sext<21,16>(sd_out_q_V_reg_1521.read());
}

void qam_dem_top_mounstrito::thread_OP2_V_i_cast_fu_325_p1() {
    OP2_V_i_cast_fu_325_p1 = esl_sext<27,12>(ph_in_i_V.read());
}

void qam_dem_top_mounstrito::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_106() {
    ap_sig_bdd_106 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_114() {
    ap_sig_bdd_114 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_122() {
    ap_sig_bdd_122 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_148() {
    ap_sig_bdd_148 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_163() {
    ap_sig_bdd_163 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_176() {
    ap_sig_bdd_176 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_197() {
    ap_sig_bdd_197 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_210() {
    ap_sig_bdd_210 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_221() {
    ap_sig_bdd_221 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_234() {
    ap_sig_bdd_234 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_247() {
    ap_sig_bdd_247 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_275() {
    ap_sig_bdd_275 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_34() {
    ap_sig_bdd_34 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_82() {
    ap_sig_bdd_82 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_89() {
    ap_sig_bdd_89 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void qam_dem_top_mounstrito::thread_ap_sig_bdd_99() {
    ap_sig_bdd_99 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_bdd_197.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_bdd_210.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_bdd_221.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_bdd_234.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_bdd_247.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_bdd_275.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_34.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_82.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_99.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_89.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_106.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_148.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_163.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_176.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_114.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_brmerge1_i_fu_893_p2() {
    brmerge1_i_fu_893_p2 = (overflow_3_reg_1607.read() | underflow_4_not_i_fu_888_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge39_i1_i_fu_426_p2() {
    brmerge39_i1_i_fu_426_p2 = (p_not38_i1_i_fu_420_p2.read() | newsignbit_0_not_i1_i_fu_414_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge39_i_i1_fu_732_p2() {
    brmerge39_i_i1_fu_732_p2 = (p_not38_i_i1_fu_727_p2.read() | newsignbit_0_not_i_i1_fu_722_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge39_i_i_fu_556_p2() {
    brmerge39_i_i_fu_556_p2 = (p_not38_i_i_fu_551_p2.read() | newsignbit_0_not_i_i_fu_546_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge39_i_i_i_fu_872_p2() {
    brmerge39_i_i_i_fu_872_p2 = (p_not38_i_i_i_fu_866_p2.read() | newsignbit_0_not_i_i_i_fu_860_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge8_i_fu_447_p2() {
    brmerge8_i_fu_447_p2 = (overflow_reg_1503.read() | underflow_not_i_fu_442_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge9_i_fu_579_p2() {
    brmerge9_i_fu_579_p2 = (overflow_1_fu_540_p2.read() | underflow_1_not_i_fu_573_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge_i1_fu_1115_p2() {
    brmerge_i1_fu_1115_p2 = (newsignbit_4_fu_1083_p3.read() | isneg_not_i_fu_1109_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge_i1_i_fu_396_p2() {
    brmerge_i1_i_fu_396_p2 = (newsignbit_fu_372_p3.read() | p_not_i1_i_fu_390_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge_i_fu_755_p2() {
    brmerge_i_fu_755_p2 = (overflow_2_fu_716_p2.read() | underflow_not_i1_fu_749_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge_i_i1_fu_706_p2() {
    brmerge_i_i1_fu_706_p2 = (newsignbit_2_reg_1574.read() | p_not_i_i9_fu_701_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge_i_i1_i_fu_438_p2() {
    brmerge_i_i1_i_fu_438_p2 = (underflow_reg_1509.read() | overflow_reg_1503.read());
}

void qam_dem_top_mounstrito::thread_brmerge_i_i4_i_fu_842_p2() {
    brmerge_i_i4_i_fu_842_p2 = (newsignbit_3_fu_818_p3.read() | p_not_i_i_i_fu_836_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge_i_i_fu_530_p2() {
    brmerge_i_i_fu_530_p2 = (newsignbit_1_reg_1533.read() | p_not_i_i_fu_525_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge_i_i_i1_fu_743_p2() {
    brmerge_i_i_i1_fu_743_p2 = (underflow_2_fu_738_p2.read() | overflow_2_fu_716_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge_i_i_i2_fu_1103_p2() {
    brmerge_i_i_i2_fu_1103_p2 = (isneg_4_fu_1071_p3.read() ^ newsignbit_4_fu_1083_p3.read());
}

void qam_dem_top_mounstrito::thread_brmerge_i_i_i_fu_567_p2() {
    brmerge_i_i_i_fu_567_p2 = (underflow_1_fu_562_p2.read() | overflow_1_fu_540_p2.read());
}

void qam_dem_top_mounstrito::thread_brmerge_i_i_i_i_fu_884_p2() {
    brmerge_i_i_i_i_fu_884_p2 = (underflow_3_reg_1613.read() | overflow_3_reg_1607.read());
}

void qam_dem_top_mounstrito::thread_cos_adr_V_3_fu_1283_p2() {
    cos_adr_V_3_fu_1283_p2 = (sin_adr_V_reg_1660.read() ^ ap_const_lv10_3FF);
}

void qam_dem_top_mounstrito::thread_cos_adr_V_fu_1288_p3() {
    cos_adr_V_fu_1288_p3 = (!tmp_26_reg_1654.read()[0].is_01())? sc_lv<10>(): ((tmp_26_reg_1654.read()[0].to_bool())? cos_adr_V_3_fu_1283_p2.read(): sin_adr_V_reg_1660.read());
}

void qam_dem_top_mounstrito::thread_cos_lut_address0() {
    cos_lut_address0 =  (sc_lv<10>) (tmp_23_i_fu_1300_p1.read());
}

void qam_dem_top_mounstrito::thread_cos_lut_address1() {
    cos_lut_address1 =  (sc_lv<10>) (tmp_24_i_fu_1305_p1.read());
}

void qam_dem_top_mounstrito::thread_cos_lut_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        cos_lut_ce0 = ap_const_logic_1;
    } else {
        cos_lut_ce0 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_cos_lut_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        cos_lut_ce1 = ap_const_logic_1;
    } else {
        cos_lut_ce1 = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_dout_mix_i_V() {
    dout_mix_i_V = sd_out_i_V_reg_1491.read();
}

void qam_dem_top_mounstrito::thread_dout_mix_i_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        dout_mix_i_V_ap_vld = ap_const_logic_1;
    } else {
        dout_mix_i_V_ap_vld = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_dout_mix_q_V() {
    dout_mix_q_V = sd_out_q_V_reg_1521.read();
}

void qam_dem_top_mounstrito::thread_dout_mix_q_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        dout_mix_q_V_ap_vld = ap_const_logic_1;
    } else {
        dout_mix_q_V_ap_vld = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_grp_fu_276_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !ap_sig_bdd_122.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()))) {
        grp_fu_276_ce = ap_const_logic_1;
    } else {
        grp_fu_276_ce = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_grp_fu_276_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        grp_fu_276_p0 =  (sc_lv<16>) (OP2_V_1_fu_697_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        grp_fu_276_p0 =  (sc_lv<16>) (OP2_V_fu_633_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        grp_fu_276_p0 =  (sc_lv<16>) (tmp_1_reg_1486.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        grp_fu_276_p0 =  (sc_lv<16>) (OP1_V_i_cast_reg_1471.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        grp_fu_276_p0 =  (sc_lv<16>) (tmp_1_fu_335_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        grp_fu_276_p0 =  (sc_lv<16>) (OP1_V_i_cast_fu_320_p1.read());
    } else {
        grp_fu_276_p0 = "XXXXXXXXXXXXXXXX";
    }
}

void qam_dem_top_mounstrito::thread_grp_fu_276_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        grp_fu_276_p1 =  (sc_lv<12>) (OP1_V_1_fu_692_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        grp_fu_276_p1 =  (sc_lv<12>) (OP1_V_fu_628_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        grp_fu_276_p1 =  (sc_lv<12>) (OP2_V_i_cast_reg_1476.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        grp_fu_276_p1 =  (sc_lv<12>) (OP2_V_1_i_cast_reg_1481.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        grp_fu_276_p1 =  (sc_lv<12>) (OP2_V_1_i_cast_fu_330_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        grp_fu_276_p1 =  (sc_lv<12>) (OP2_V_i_cast_fu_325_p1.read());
    } else {
        grp_fu_276_p1 =  (sc_lv<12>) ("XXXXXXXXXXXX");
    }
}

void qam_dem_top_mounstrito::thread_isNeg_1_fu_995_p3() {
    isNeg_1_fu_995_p3 = sh_assign_1_fu_989_p2.read().range(8, 8);
}

void qam_dem_top_mounstrito::thread_isNeg_2_fu_1160_p3() {
    isNeg_2_fu_1160_p3 = control_lf_out_gain.read().range(7, 7);
}

void qam_dem_top_mounstrito::thread_isNeg_fu_927_p3() {
    isNeg_fu_927_p3 = control_lf_p.read().range(7, 7);
}

void qam_dem_top_mounstrito::thread_isneg_2_fu_656_p1() {
    isneg_2_fu_656_p1 =  (sc_lv<21>) (grp_fu_276_p2.read());
}

void qam_dem_top_mounstrito::thread_isneg_3_fu_800_p3() {
    isneg_3_fu_800_p3 = p_Val2_23_fu_794_p2.read().range(20, 20);
}

void qam_dem_top_mounstrito::thread_isneg_4_fu_1071_p3() {
    isneg_4_fu_1071_p3 = p_Val2_27_fu_1065_p2.read().range(28, 28);
}

void qam_dem_top_mounstrito::thread_isneg_fu_364_p3() {
    isneg_fu_364_p3 = p_Val2_1_fu_348_p2.read().range(26, 26);
}

void qam_dem_top_mounstrito::thread_isneg_not_i_fu_1109_p2() {
    isneg_not_i_fu_1109_p2 = (isneg_4_fu_1071_p3.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_loop_integ_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        loop_integ_V = p_Val2_41_fu_1145_p3.read();
    } else {
        loop_integ_V = loop_integ_V_preg.read();
    }
}

void qam_dem_top_mounstrito::thread_loop_integ_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        loop_integ_V_ap_vld = ap_const_logic_1;
    } else {
        loop_integ_V_ap_vld = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_newsignbit_0_not_i1_i_fu_414_p2() {
    newsignbit_0_not_i1_i_fu_414_p2 = (newsignbit_fu_372_p3.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_newsignbit_0_not_i_i1_fu_722_p2() {
    newsignbit_0_not_i_i1_fu_722_p2 = (newsignbit_2_reg_1574.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_newsignbit_0_not_i_i_fu_546_p2() {
    newsignbit_0_not_i_i_fu_546_p2 = (newsignbit_1_reg_1533.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_newsignbit_0_not_i_i_i_fu_860_p2() {
    newsignbit_0_not_i_i_i_fu_860_p2 = (newsignbit_3_fu_818_p3.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_newsignbit_2_fu_674_p1() {
    newsignbit_2_fu_674_p1 =  (sc_lv<21>) (grp_fu_276_p2.read());
}

void qam_dem_top_mounstrito::thread_newsignbit_3_fu_818_p3() {
    newsignbit_3_fu_818_p3 = p_Val2_23_fu_794_p2.read().range(18, 18);
}

void qam_dem_top_mounstrito::thread_newsignbit_4_fu_1083_p3() {
    newsignbit_4_fu_1083_p3 = p_Val2_27_fu_1065_p2.read().range(27, 27);
}

void qam_dem_top_mounstrito::thread_newsignbit_fu_372_p3() {
    newsignbit_fu_372_p3 = p_Val2_1_fu_348_p2.read().range(24, 24);
}

void qam_dem_top_mounstrito::thread_not_brmerge_i_i1_i_fu_452_p2() {
    not_brmerge_i_i1_i_fu_452_p2 = (brmerge_i_i1_i_fu_438_p2.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_not_brmerge_i_i_i_fu_604_p2() {
    not_brmerge_i_i_i_fu_604_p2 = (brmerge_i_i_i_fu_567_p2.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_or_cond_fu_1375_p2() {
    or_cond_fu_1375_p2 = (sel_tmp7_i_fu_1369_p2.read() | sel_tmp4_i_fu_1357_p2.read());
}

void qam_dem_top_mounstrito::thread_overflow_1_fu_540_p2() {
    overflow_1_fu_540_p2 = (brmerge_i_i_fu_530_p2.read() & tmp_7_i_fu_535_p2.read());
}

void qam_dem_top_mounstrito::thread_overflow_2_fu_716_p2() {
    overflow_2_fu_716_p2 = (brmerge_i_i1_fu_706_p2.read() & tmp_8_i_fu_711_p2.read());
}

void qam_dem_top_mounstrito::thread_overflow_3_fu_854_p2() {
    overflow_3_fu_854_p2 = (brmerge_i_i4_i_fu_842_p2.read() & tmp_3_i1_fu_848_p2.read());
}

void qam_dem_top_mounstrito::thread_overflow_fu_408_p2() {
    overflow_fu_408_p2 = (brmerge_i1_i_fu_396_p2.read() & tmp_5_i_fu_402_p2.read());
}

void qam_dem_top_mounstrito::thread_p_Result_2_fu_644_p5() {
    p_Result_2_fu_644_p5 = esl_partset<5,5,2,32,32>(ap_const_lv5_0, tmp_1_i3_fu_637_p3.read(), ap_const_lv32_3, ap_const_lv32_4);
}

void qam_dem_top_mounstrito::thread_p_Result_i8_fu_682_p1() {
    p_Result_i8_fu_682_p1 =  (sc_lv<21>) (grp_fu_276_p2.read());
}

void qam_dem_top_mounstrito::thread_p_Result_i_fu_380_p4() {
    p_Result_i_fu_380_p4 = p_Val2_1_fu_348_p2.read().range(26, 25);
}

void qam_dem_top_mounstrito::thread_p_Result_s_fu_592_p5() {
    p_Result_s_fu_592_p5 = esl_partset<5,5,2,32,32>(ap_const_lv5_0, tmp_i2_fu_585_p3.read(), ap_const_lv32_3, ap_const_lv32_4);
}

void qam_dem_top_mounstrito::thread_p_Val2_1_fu_348_p2() {
    p_Val2_1_fu_348_p2 = (!tmp_6_i_fu_340_p3.read().is_01() || !reg_316.read().is_01())? sc_lv<27>(): (sc_biguint<27>(tmp_6_i_fu_340_p3.read()) - sc_bigint<27>(reg_316.read()));
}

void qam_dem_top_mounstrito::thread_p_Val2_1_i_fu_905_p3() {
    p_Val2_1_i_fu_905_p3 = (!underflow_3_reg_1613.read()[0].is_01())? sc_lv<14>(): ((underflow_3_reg_1613.read()[0].to_bool())? ap_const_lv14_2000: p_Val2_24_reg_1601.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_21_mux_i_fu_761_p3() {
    p_Val2_21_mux_i_fu_761_p3 = (!brmerge_i_i_i1_fu_743_p2.read()[0].is_01())? sc_lv<14>(): ((brmerge_i_i_i1_fu_743_p2.read()[0].to_bool())? ap_const_lv14_1FFF: p_Val2_9_reg_1568.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_23_fu_794_p1() {
    p_Val2_23_fu_794_p1 =  (sc_lv<21>) (reg_316.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_23_fu_794_p2() {
    p_Val2_23_fu_794_p2 = (!tmp_10_cast_i_fu_790_p1.read().is_01() || !p_Val2_23_fu_794_p1.read().is_01())? sc_lv<21>(): (sc_bigint<21>(tmp_10_cast_i_fu_790_p1.read()) - sc_bigint<21>(p_Val2_23_fu_794_p1.read()));
}

void qam_dem_top_mounstrito::thread_p_Val2_26_fu_977_p3() {
    p_Val2_26_fu_977_p3 = (!isNeg_fu_927_p3.read()[0].is_01())? sc_lv<28>(): ((isNeg_fu_927_p3.read()[0].to_bool())? tmp_16_fu_973_p1.read(): tmp_7_i1_fu_967_p2.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_27_fu_1065_p2() {
    p_Val2_27_fu_1065_p2 = (!tmp_12_i_fu_1058_p1.read().is_01() || !tmp_13_i_fu_1062_p1.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp_12_i_fu_1058_p1.read()) + sc_bigint<29>(tmp_13_i_fu_1062_p1.read()));
}

void qam_dem_top_mounstrito::thread_p_Val2_28_mux_i_fu_1121_p3() {
    p_Val2_28_mux_i_fu_1121_p3 = (!brmerge_i_i_i2_fu_1103_p2.read()[0].is_01())? sc_lv<28>(): ((brmerge_i_i_i2_fu_1103_p2.read()[0].to_bool())? ap_const_lv28_7FFFFFF: p_Val2_29_fu_1079_p1.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_29_fu_1079_p1() {
    p_Val2_29_fu_1079_p1 = p_Val2_27_fu_1065_p2.read().range(28-1, 0);
}

void qam_dem_top_mounstrito::thread_p_Val2_31_cast_i_fu_1314_p1() {
    p_Val2_31_cast_i_fu_1314_p1 = esl_zext<16,15>(cos_lut_q1.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_32_cast_i_fu_1310_p1() {
    p_Val2_32_cast_i_fu_1310_p1 = esl_zext<16,15>(cos_lut_q0.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_33_fu_1206_p3() {
    p_Val2_33_fu_1206_p3 = (!isNeg_2_reg_1636.read()[0].is_01())? sc_lv<28>(): ((isNeg_2_reg_1636.read()[0].to_bool())? tmp_25_fu_1202_p1.read(): tmp_20_i_fu_1197_p2.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_34_fu_1233_p2() {
    p_Val2_34_fu_1233_p2 = (!tmp_35_cast_i_fu_1225_p1.read().is_01() || !tmp_21_i_fu_1229_p1.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp_35_cast_i_fu_1225_p1.read()) - sc_biguint<29>(tmp_21_i_fu_1229_p1.read()));
}

void qam_dem_top_mounstrito::thread_p_Val2_3_fu_483_p2() {
    p_Val2_3_fu_483_p2 = (!tmp_3_i_fu_475_p3.read().is_01() || !reg_316.read().is_01())? sc_lv<27>(): (sc_biguint<27>(tmp_3_i_fu_475_p3.read()) + sc_bigint<27>(reg_316.read()));
}

void qam_dem_top_mounstrito::thread_p_Val2_41_fu_1145_p3() {
    p_Val2_41_fu_1145_p3 = (!control_reg_clr.read()[0].is_01())? sc_lv<28>(): ((control_reg_clr.read()[0].to_bool())? control_reg_init_V.read(): p_Val2_5_fu_1053_p2.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_4_fu_1041_p3() {
    p_Val2_4_fu_1041_p3 = (!isNeg_1_fu_995_p3.read()[0].is_01())? sc_lv<28>(): ((isNeg_1_fu_995_p3.read()[0].to_bool())? tmp_18_fu_1037_p1.read(): tmp_11_i_fu_1031_p2.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_5_fu_1053_p2() {
    p_Val2_5_fu_1053_p2 = (!i_reg_V.read().is_01() || !p_Val2_4_reg_1625.read().is_01())? sc_lv<28>(): (sc_biguint<28>(i_reg_V.read()) + sc_biguint<28>(p_Val2_4_reg_1625.read()));
}

void qam_dem_top_mounstrito::thread_p_Val2_9_fu_664_p1() {
    p_Val2_9_fu_664_p1 =  (sc_lv<21>) (grp_fu_276_p2.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_i1_fu_768_p3() {
    p_Val2_i1_fu_768_p3 = (!underflow_2_fu_738_p2.read()[0].is_01())? sc_lv<14>(): ((underflow_2_fu_738_p2.read()[0].to_bool())? ap_const_lv14_2000: p_Val2_9_reg_1568.read());
}

void qam_dem_top_mounstrito::thread_p_Val2_i2_fu_1129_p3() {
    p_Val2_i2_fu_1129_p3 = (!underflow_4_fu_1097_p2.read()[0].is_01())? sc_lv<28>(): ((underflow_4_fu_1097_p2.read()[0].to_bool())? ap_const_lv28_8000000: p_Val2_29_fu_1079_p1.read());
}

void qam_dem_top_mounstrito::thread_p_not38_i1_i_fu_420_p2() {
    p_not38_i1_i_fu_420_p2 = (!p_Result_i_fu_380_p4.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_i_fu_380_p4.read() != ap_const_lv2_3);
}

void qam_dem_top_mounstrito::thread_p_not38_i_i1_fu_727_p2() {
    p_not38_i_i1_fu_727_p2 = (!p_Result_i8_reg_1580.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_i8_reg_1580.read() != ap_const_lv2_3);
}

void qam_dem_top_mounstrito::thread_p_not38_i_i_fu_551_p2() {
    p_not38_i_i_fu_551_p2 = (!p_Result_1_i_reg_1541.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_1_i_reg_1541.read() != ap_const_lv2_3);
}

void qam_dem_top_mounstrito::thread_p_not38_i_i_i_fu_866_p2() {
    p_not38_i_i_i_fu_866_p2 = (!tmp_7_fu_826_p4.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(tmp_7_fu_826_p4.read() != ap_const_lv2_3);
}

void qam_dem_top_mounstrito::thread_p_not_i1_i_fu_390_p2() {
    p_not_i1_i_fu_390_p2 = (!p_Result_i_fu_380_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_i_fu_380_p4.read() != ap_const_lv2_0);
}

void qam_dem_top_mounstrito::thread_p_not_i_i9_fu_701_p2() {
    p_not_i_i9_fu_701_p2 = (!p_Result_i8_reg_1580.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_i8_reg_1580.read() != ap_const_lv2_0);
}

void qam_dem_top_mounstrito::thread_p_not_i_i_fu_525_p2() {
    p_not_i_i_fu_525_p2 = (!p_Result_1_i_reg_1541.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_1_i_reg_1541.read() != ap_const_lv2_0);
}

void qam_dem_top_mounstrito::thread_p_not_i_i_i_fu_836_p2() {
    p_not_i_i_i_fu_836_p2 = (!tmp_7_fu_826_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_7_fu_826_p4.read() != ap_const_lv2_0);
}

void qam_dem_top_mounstrito::thread_ph_out_i_V() {
    ph_out_i_V = (!sel_tmp7_i_fu_1369_p2.read()[0].is_01())? sc_lv<12>(): ((sel_tmp7_i_fu_1369_p2.read()[0].to_bool())? tmp_12_fu_1391_p1.read(): tmp_28_fu_1405_p3.read());
}

void qam_dem_top_mounstrito::thread_ph_out_i_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        ph_out_i_V_ap_vld = ap_const_logic_1;
    } else {
        ph_out_i_V_ap_vld = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_ph_out_q_V() {
    ph_out_q_V = (!or_cond_fu_1375_p2.read()[0].is_01())? sc_lv<12>(): ((or_cond_fu_1375_p2.read()[0].to_bool())? tmp_32_fu_1446_p3.read(): tmp_33_fu_1454_p3.read());
}

void qam_dem_top_mounstrito::thread_ph_out_q_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        ph_out_q_V_ap_vld = ap_const_logic_1;
    } else {
        ph_out_q_V_ap_vld = ap_const_logic_0;
    }
}

void qam_dem_top_mounstrito::thread_sel_tmp3_demorgan_i_fu_1345_p2() {
    sel_tmp3_demorgan_i_fu_1345_p2 = (tmp_25_i_fu_1318_p2.read() | tmp_26_i_fu_1323_p2.read());
}

void qam_dem_top_mounstrito::thread_sel_tmp3_i_fu_1351_p2() {
    sel_tmp3_i_fu_1351_p2 = (sel_tmp3_demorgan_i_fu_1345_p2.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_sel_tmp4_i_fu_1357_p2() {
    sel_tmp4_i_fu_1357_p2 = (tmp_27_i_fu_1328_p2.read() & sel_tmp3_i_fu_1351_p2.read());
}

void qam_dem_top_mounstrito::thread_sel_tmp6_i_fu_1363_p2() {
    sel_tmp6_i_fu_1363_p2 = (tmp_25_i_fu_1318_p2.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_sel_tmp7_i_fu_1369_p2() {
    sel_tmp7_i_fu_1369_p2 = (tmp_26_i_fu_1323_p2.read() & sel_tmp6_i_fu_1363_p2.read());
}

void qam_dem_top_mounstrito::thread_sel_tmp_i_fu_1339_p2() {
    sel_tmp_i_fu_1339_p2 = (!ap_const_lv16_0.is_01() || !p_Val2_32_cast_i_fu_1310_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(p_Val2_32_cast_i_fu_1310_p1.read()));
}

void qam_dem_top_mounstrito::thread_sh_assign_1_cast6_i_fu_949_p1() {
    sh_assign_1_cast6_i_fu_949_p1 = esl_zext<28,8>(sh_assign_fu_941_p3.read());
}

void qam_dem_top_mounstrito::thread_sh_assign_1_cast_i_fu_953_p1() {
    sh_assign_1_cast_i_fu_953_p1 = esl_zext<32,8>(sh_assign_fu_941_p3.read());
}

void qam_dem_top_mounstrito::thread_sh_assign_1_fu_989_p2() {
    sh_assign_1_fu_989_p2 = (!tmp_19_cast_i_fu_985_p1.read().is_01() || !ap_const_lv9_9.is_01())? sc_lv<9>(): (sc_bigint<9>(tmp_19_cast_i_fu_985_p1.read()) + sc_biguint<9>(ap_const_lv9_9));
}

void qam_dem_top_mounstrito::thread_sh_assign_2_fu_1009_p3() {
    sh_assign_2_fu_1009_p3 = (!isNeg_1_fu_995_p3.read()[0].is_01())? sc_lv<9>(): ((isNeg_1_fu_995_p3.read()[0].to_bool())? tmp_8_i1_fu_1003_p2.read(): sh_assign_1_fu_989_p2.read());
}

void qam_dem_top_mounstrito::thread_sh_assign_3_cast5_i_fu_1017_p1() {
    sh_assign_3_cast5_i_fu_1017_p1 = esl_sext<28,9>(sh_assign_2_fu_1009_p3.read());
}

void qam_dem_top_mounstrito::thread_sh_assign_3_cast_i_fu_1021_p1() {
    sh_assign_3_cast_i_fu_1021_p1 = esl_sext<32,9>(sh_assign_2_fu_1009_p3.read());
}

void qam_dem_top_mounstrito::thread_sh_assign_3_fu_1174_p3() {
    sh_assign_3_fu_1174_p3 = (!isNeg_2_fu_1160_p3.read()[0].is_01())? sc_lv<8>(): ((isNeg_2_fu_1160_p3.read()[0].to_bool())? tmp_17_i_fu_1168_p2.read(): control_lf_out_gain.read());
}

void qam_dem_top_mounstrito::thread_sh_assign_5_cast3_i_fu_1182_p1() {
    sh_assign_5_cast3_i_fu_1182_p1 = esl_zext<28,8>(sh_assign_3_reg_1641.read());
}

void qam_dem_top_mounstrito::thread_sh_assign_5_cast_i_fu_1185_p1() {
    sh_assign_5_cast_i_fu_1185_p1 = esl_zext<32,8>(sh_assign_3_reg_1641.read());
}

void qam_dem_top_mounstrito::thread_sh_assign_fu_941_p3() {
    sh_assign_fu_941_p3 = (!isNeg_fu_927_p3.read()[0].is_01())? sc_lv<8>(): ((isNeg_fu_927_p3.read()[0].to_bool())? tmp_4_i_fu_935_p2.read(): control_lf_p.read());
}

void qam_dem_top_mounstrito::thread_sin_adr_V_1_fu_1294_p3() {
    sin_adr_V_1_fu_1294_p3 = (!tmp_26_reg_1654.read()[0].is_01())? sc_lv<10>(): ((tmp_26_reg_1654.read()[0].to_bool())? sin_adr_V_reg_1660.read(): cos_adr_V_3_fu_1283_p2.read());
}

void qam_dem_top_mounstrito::thread_sin_out_V_fu_1333_p2() {
    sin_out_V_fu_1333_p2 = (!ap_const_lv16_0.is_01() || !p_Val2_31_cast_i_fu_1314_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(p_Val2_31_cast_i_fu_1314_p1.read()));
}

void qam_dem_top_mounstrito::thread_ssdm_int_V_write_assign_fu_898_p3() {
    ssdm_int_V_write_assign_fu_898_p3 = (!brmerge_i_i_i_i_fu_884_p2.read()[0].is_01())? sc_lv<14>(): ((brmerge_i_i_i_i_fu_884_p2.read()[0].to_bool())? ap_const_lv14_1FFF: p_Val2_24_reg_1601.read());
}

void qam_dem_top_mounstrito::thread_tmp_10_cast_i_fu_790_p1() {
    tmp_10_cast_i_fu_790_p1 = esl_sext<21,19>(tmp_1_i1_fu_783_p3.read());
}

void qam_dem_top_mounstrito::thread_tmp_10_fu_911_p3() {
    tmp_10_fu_911_p3 = (!brmerge1_i_fu_893_p2.read()[0].is_01())? sc_lv<14>(): ((brmerge1_i_fu_893_p2.read()[0].to_bool())? ssdm_int_V_write_assign_fu_898_p3.read(): p_Val2_1_i_fu_905_p3.read());
}

void qam_dem_top_mounstrito::thread_tmp_10_i_fu_1025_p2() {
    tmp_10_i_fu_1025_p2 = (!sh_assign_3_cast_i_fu_1021_p1.read().is_01())? sc_lv<32>(): tmp_5_i1_fu_957_p1.read() << (unsigned short)sh_assign_3_cast_i_fu_1021_p1.read().to_uint();
}

void qam_dem_top_mounstrito::thread_tmp_11_fu_1381_p4() {
    tmp_11_fu_1381_p4 = cos_lut_q0.read().range(14, 4);
}

void qam_dem_top_mounstrito::thread_tmp_11_i_fu_1031_p2() {
    tmp_11_i_fu_1031_p2 = (!tmp_i1_fu_919_p3.read().is_01() || !sh_assign_3_cast5_i_fu_1017_p1.read().is_01())? sc_lv<28>(): sc_bigint<28>(tmp_i1_fu_919_p3.read()) >> (unsigned short)sh_assign_3_cast5_i_fu_1017_p1.read().to_uint();
}

void qam_dem_top_mounstrito::thread_tmp_12_fu_1391_p1() {
    tmp_12_fu_1391_p1 = esl_zext<12,11>(tmp_11_fu_1381_p4.read());
}

void qam_dem_top_mounstrito::thread_tmp_12_i_fu_1058_p1() {
    tmp_12_i_fu_1058_p1 = esl_sext<29,28>(p_Val2_5_fu_1053_p2.read());
}

void qam_dem_top_mounstrito::thread_tmp_13_i_fu_1062_p1() {
    tmp_13_i_fu_1062_p1 = esl_sext<29,28>(p_Val2_26_reg_1620.read());
}

void qam_dem_top_mounstrito::thread_tmp_15_i_fu_1091_p2() {
    tmp_15_i_fu_1091_p2 = (newsignbit_4_fu_1083_p3.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_tmp_16_fu_973_p1() {
    tmp_16_fu_973_p1 = tmp_6_i2_fu_961_p2.read().range(28-1, 0);
}

void qam_dem_top_mounstrito::thread_tmp_16_i_fu_1137_p3() {
    tmp_16_i_fu_1137_p3 = (!brmerge_i1_fu_1115_p2.read()[0].is_01())? sc_lv<28>(): ((brmerge_i1_fu_1115_p2.read()[0].to_bool())? p_Val2_28_mux_i_fu_1121_p3.read(): p_Val2_i2_fu_1129_p3.read());
}

void qam_dem_top_mounstrito::thread_tmp_17_i_fu_1168_p2() {
    tmp_17_i_fu_1168_p2 = (!ap_const_lv8_0.is_01() || !control_lf_out_gain.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_0) - sc_biguint<8>(control_lf_out_gain.read()));
}

void qam_dem_top_mounstrito::thread_tmp_18_fu_1037_p1() {
    tmp_18_fu_1037_p1 = tmp_10_i_fu_1025_p2.read().range(28-1, 0);
}

void qam_dem_top_mounstrito::thread_tmp_18_i_fu_1188_p1() {
    tmp_18_i_fu_1188_p1 = esl_sext<32,28>(tmp_16_i_reg_1630.read());
}

void qam_dem_top_mounstrito::thread_tmp_19_cast_i_fu_985_p1() {
    tmp_19_cast_i_fu_985_p1 = esl_sext<9,8>(control_lf_i.read());
}

void qam_dem_top_mounstrito::thread_tmp_19_i_fu_1191_p2() {
    tmp_19_i_fu_1191_p2 = (!sh_assign_5_cast_i_fu_1185_p1.read().is_01())? sc_lv<32>(): tmp_18_i_fu_1188_p1.read() << (unsigned short)sh_assign_5_cast_i_fu_1185_p1.read().to_uint();
}

void qam_dem_top_mounstrito::thread_tmp_1_fu_335_p1() {
    tmp_1_fu_335_p1 = esl_sext<27,16>(din_q_V.read());
}

void qam_dem_top_mounstrito::thread_tmp_1_i1_fu_783_p3() {
    tmp_1_i1_fu_783_p3 = esl_concat<14,5>(tmp_9_reg_1596.read(), ap_const_lv5_0);
}

void qam_dem_top_mounstrito::thread_tmp_1_i3_fu_637_p3() {
    tmp_1_i3_fu_637_p3 = esl_concat<1,1>(tmp_6_reg_1547.read(), ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_tmp_20_i_fu_1197_p2() {
    tmp_20_i_fu_1197_p2 = (!tmp_16_i_reg_1630.read().is_01() || !sh_assign_5_cast3_i_fu_1182_p1.read().is_01())? sc_lv<28>(): sc_bigint<28>(tmp_16_i_reg_1630.read()) >> (unsigned short)sh_assign_5_cast3_i_fu_1182_p1.read().to_uint();
}

void qam_dem_top_mounstrito::thread_tmp_21_i_fu_1229_p1() {
    tmp_21_i_fu_1229_p1 = esl_zext<29,28>(p_Val2_33_fu_1206_p3.read());
}

void qam_dem_top_mounstrito::thread_tmp_23_i_fu_1300_p1() {
    tmp_23_i_fu_1300_p1 = esl_zext<64,10>(cos_adr_V_fu_1288_p3.read());
}

void qam_dem_top_mounstrito::thread_tmp_24_i_fu_1305_p1() {
    tmp_24_i_fu_1305_p1 = esl_zext<64,10>(sin_adr_V_1_fu_1294_p3.read());
}

void qam_dem_top_mounstrito::thread_tmp_25_fu_1202_p1() {
    tmp_25_fu_1202_p1 = tmp_19_i_fu_1191_p2.read().range(28-1, 0);
}

void qam_dem_top_mounstrito::thread_tmp_25_i_fu_1318_p2() {
    tmp_25_i_fu_1318_p2 = (!msb_V_reg_1647.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(msb_V_reg_1647.read() == ap_const_lv2_1);
}

void qam_dem_top_mounstrito::thread_tmp_26_i_fu_1323_p2() {
    tmp_26_i_fu_1323_p2 = (!msb_V_reg_1647.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(msb_V_reg_1647.read() == ap_const_lv2_0);
}

void qam_dem_top_mounstrito::thread_tmp_27_fu_1395_p4() {
    tmp_27_fu_1395_p4 = sel_tmp_i_fu_1339_p2.read().range(15, 4);
}

void qam_dem_top_mounstrito::thread_tmp_27_i_fu_1328_p2() {
    tmp_27_i_fu_1328_p2 = (!msb_V_reg_1647.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(msb_V_reg_1647.read() == ap_const_lv2_3);
}

void qam_dem_top_mounstrito::thread_tmp_28_fu_1405_p3() {
    tmp_28_fu_1405_p3 = (!sel_tmp4_i_fu_1357_p2.read()[0].is_01())? sc_lv<12>(): ((sel_tmp4_i_fu_1357_p2.read()[0].to_bool())? tmp_12_fu_1391_p1.read(): tmp_27_fu_1395_p4.read());
}

void qam_dem_top_mounstrito::thread_tmp_29_fu_1422_p4() {
    tmp_29_fu_1422_p4 = cos_lut_q1.read().range(14, 4);
}

void qam_dem_top_mounstrito::thread_tmp_30_fu_1432_p1() {
    tmp_30_fu_1432_p1 = esl_zext<12,11>(tmp_29_fu_1422_p4.read());
}

void qam_dem_top_mounstrito::thread_tmp_31_fu_1436_p4() {
    tmp_31_fu_1436_p4 = sin_out_V_fu_1333_p2.read().range(15, 4);
}

void qam_dem_top_mounstrito::thread_tmp_32_fu_1446_p3() {
    tmp_32_fu_1446_p3 = (!sel_tmp7_i_fu_1369_p2.read()[0].is_01())? sc_lv<12>(): ((sel_tmp7_i_fu_1369_p2.read()[0].to_bool())? tmp_30_fu_1432_p1.read(): tmp_31_fu_1436_p4.read());
}

void qam_dem_top_mounstrito::thread_tmp_33_fu_1454_p3() {
    tmp_33_fu_1454_p3 = (!tmp_25_i_fu_1318_p2.read()[0].is_01())? sc_lv<12>(): ((tmp_25_i_fu_1318_p2.read()[0].to_bool())? tmp_30_fu_1432_p1.read(): tmp_31_fu_1436_p4.read());
}

void qam_dem_top_mounstrito::thread_tmp_35_cast_i_fu_1225_p1() {
    tmp_35_cast_i_fu_1225_p1 = esl_sext<29,27>(tmp_i2_15_fu_1217_p3.read());
}

void qam_dem_top_mounstrito::thread_tmp_3_fu_467_p3() {
    tmp_3_fu_467_p3 = (!brmerge8_i_fu_447_p2.read()[0].is_01())? sc_lv<1>(): ((brmerge8_i_fu_447_p2.read()[0].to_bool())? tmp_5_fu_458_p2.read(): tmp_s_fu_463_p2.read());
}

void qam_dem_top_mounstrito::thread_tmp_3_i1_fu_848_p2() {
    tmp_3_i1_fu_848_p2 = (isneg_3_fu_800_p3.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_tmp_3_i_fu_475_p3() {
    tmp_3_i_fu_475_p3 = esl_concat<16,11>(reg_312.read(), ap_const_lv11_0);
}

void qam_dem_top_mounstrito::thread_tmp_4_fu_610_p2() {
    tmp_4_fu_610_p2 = (newsignbit_1_reg_1533.read() & not_brmerge_i_i_i_fu_604_p2.read());
}

void qam_dem_top_mounstrito::thread_tmp_4_i_fu_935_p2() {
    tmp_4_i_fu_935_p2 = (!ap_const_lv8_0.is_01() || !control_lf_p.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_0) - sc_biguint<8>(control_lf_p.read()));
}

void qam_dem_top_mounstrito::thread_tmp_5_fu_458_p2() {
    tmp_5_fu_458_p2 = (newsignbit_reg_1497.read() & not_brmerge_i_i1_i_fu_452_p2.read());
}

void qam_dem_top_mounstrito::thread_tmp_5_i1_fu_957_p1() {
    tmp_5_i1_fu_957_p1 = esl_sext<32,28>(tmp_i1_fu_919_p3.read());
}

void qam_dem_top_mounstrito::thread_tmp_5_i_fu_402_p2() {
    tmp_5_i_fu_402_p2 = (isneg_fu_364_p3.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_tmp_6_fu_620_p3() {
    tmp_6_fu_620_p3 = (!brmerge9_i_fu_579_p2.read()[0].is_01())? sc_lv<1>(): ((brmerge9_i_fu_579_p2.read()[0].to_bool())? tmp_4_fu_610_p2.read(): tmp_8_fu_615_p2.read());
}

void qam_dem_top_mounstrito::thread_tmp_6_i2_fu_961_p2() {
    tmp_6_i2_fu_961_p2 = (!sh_assign_1_cast_i_fu_953_p1.read().is_01())? sc_lv<32>(): tmp_5_i1_fu_957_p1.read() << (unsigned short)sh_assign_1_cast_i_fu_953_p1.read().to_uint();
}

void qam_dem_top_mounstrito::thread_tmp_6_i_fu_340_p3() {
    tmp_6_i_fu_340_p3 = esl_concat<16,11>(reg_312.read(), ap_const_lv11_0);
}

void qam_dem_top_mounstrito::thread_tmp_7_fu_826_p4() {
    tmp_7_fu_826_p4 = p_Val2_23_fu_794_p2.read().range(20, 19);
}

void qam_dem_top_mounstrito::thread_tmp_7_i1_fu_967_p2() {
    tmp_7_i1_fu_967_p2 = (!tmp_i1_fu_919_p3.read().is_01() || !sh_assign_1_cast6_i_fu_949_p1.read().is_01())? sc_lv<28>(): sc_bigint<28>(tmp_i1_fu_919_p3.read()) >> (unsigned short)sh_assign_1_cast6_i_fu_949_p1.read().to_uint();
}

void qam_dem_top_mounstrito::thread_tmp_7_i_fu_535_p2() {
    tmp_7_i_fu_535_p2 = (isneg_1_reg_1527.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_tmp_8_fu_615_p2() {
    tmp_8_fu_615_p2 = (underflow_1_fu_562_p2.read() | newsignbit_1_reg_1533.read());
}

void qam_dem_top_mounstrito::thread_tmp_8_i1_fu_1003_p2() {
    tmp_8_i1_fu_1003_p2 = (!ap_const_lv9_1F7.is_01() || !tmp_19_cast_i_fu_985_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_1F7) - sc_bigint<9>(tmp_19_cast_i_fu_985_p1.read()));
}

void qam_dem_top_mounstrito::thread_tmp_8_i_fu_711_p2() {
    tmp_8_i_fu_711_p2 = (isneg_2_reg_1562.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_tmp_9_fu_775_p3() {
    tmp_9_fu_775_p3 = (!brmerge_i_fu_755_p2.read()[0].is_01())? sc_lv<14>(): ((brmerge_i_fu_755_p2.read()[0].to_bool())? p_Val2_21_mux_i_fu_761_p3.read(): p_Val2_i1_fu_768_p3.read());
}

void qam_dem_top_mounstrito::thread_tmp_i1_fu_919_p3() {
    tmp_i1_fu_919_p3 = esl_concat<14,14>(tmp_10_fu_911_p3.read(), ap_const_lv14_0);
}

void qam_dem_top_mounstrito::thread_tmp_i2_15_fu_1217_p3() {
    tmp_i2_15_fu_1217_p3 = esl_concat<16,11>(phase_angle_V.read(), ap_const_lv11_0);
}

void qam_dem_top_mounstrito::thread_tmp_i2_fu_585_p3() {
    tmp_i2_fu_585_p3 = esl_concat<1,1>(tmp_3_reg_1516.read(), ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_tmp_s_fu_463_p2() {
    tmp_s_fu_463_p2 = (underflow_reg_1509.read() | newsignbit_reg_1497.read());
}

void qam_dem_top_mounstrito::thread_underflow_1_fu_562_p2() {
    underflow_1_fu_562_p2 = (brmerge39_i_i_fu_556_p2.read() & isneg_1_reg_1527.read());
}

void qam_dem_top_mounstrito::thread_underflow_1_not_i_fu_573_p2() {
    underflow_1_not_i_fu_573_p2 = (underflow_1_fu_562_p2.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_underflow_2_fu_738_p2() {
    underflow_2_fu_738_p2 = (brmerge39_i_i1_fu_732_p2.read() & isneg_2_reg_1562.read());
}

void qam_dem_top_mounstrito::thread_underflow_3_fu_878_p2() {
    underflow_3_fu_878_p2 = (brmerge39_i_i_i_fu_872_p2.read() & isneg_3_fu_800_p3.read());
}

void qam_dem_top_mounstrito::thread_underflow_4_fu_1097_p2() {
    underflow_4_fu_1097_p2 = (isneg_4_fu_1071_p3.read() & tmp_15_i_fu_1091_p2.read());
}

void qam_dem_top_mounstrito::thread_underflow_4_not_i_fu_888_p2() {
    underflow_4_not_i_fu_888_p2 = (underflow_3_reg_1613.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_underflow_fu_432_p2() {
    underflow_fu_432_p2 = (brmerge39_i1_i_fu_426_p2.read() & isneg_fu_364_p3.read());
}

void qam_dem_top_mounstrito::thread_underflow_not_i1_fu_749_p2() {
    underflow_not_i1_fu_749_p2 = (underflow_2_fu_738_p2.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_underflow_not_i_fu_442_p2() {
    underflow_not_i_fu_442_p2 = (underflow_reg_1509.read() ^ ap_const_lv1_1);
}

void qam_dem_top_mounstrito::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_122.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
            break;
    }
}

}

